### ISSUE TITLE
Reloading Menyoo with scripthook crashes the whole game

### ISSUE THREAD

**Issue by TeteX1** [MAFINS/MenyooSP#128]
Trying to reload Menyoo.asi using "CTRL + R" from ScriptHook V crashes the game. To make sure it wasn't another scripts fault, I removed Menyoo.asi and the game did not crash when the reload function was invoked.

**Comment by Sainan** [comment]
This crash is due to the two threads created in the DllMain. If I have my ASI Loader terminate Menyoo's threads before unloading it, the game doesn't crash, but Menyoo stays in memory, making it unable to be loaded again (with the same file name).
