### ISSUE TITLE
Switching to Multiplayer

### ISSUE THREAD

**Issue by SimonOO7** [MAFINS/MenyooSP#129]
Hey what do i have to do to play multiplayer without mods that i dont get banned. what do i have to deinstall?

**Comment by youngezzz** [comment]
I want to know tho...

**Comment by ToxxSimon** [comment]
If you **_only_** use Menyoo (or  some other .asi mod) you'll only need to remove **dinput8.dll** and **ScriptHookV.dll** from your gta directory before going online.
Menyoo.asi won't load without ScripthookV.dll and dinput8.dll
