### ISSUE TITLE
Crashes after 1-3 minutes of game

### ISSUE THREAD

**Issue by EzicSky** [MAFINS/MenyooSP#153]
"The instruction at 0x00007ff749b8b308 accessed memory at 0x0000000000000000. The memory could not be read
"OK" - termination of the application "
(on my pc, error in another language. I translated myself, there may be inaccuracies), sometimes with this error, sometimes without, I install only scripthook and menyoo, no other mods

**Comment by ToxxicFuse** [comment]
Do you use any specific Menyoo features before this happens?

**Comment by EzicSky** [comment]
Hello! I resolve problem, sorry/ I take no correct swap file
