### ISSUE TITLE
FIXED I USED GOOGLE (IDK HOW TO DELETE THIS)

### ISSUE THREAD

**Issue by FluffyPlays22** [MAFINS/MenyooSP#172]
I've been trying to build the menu but it always gives me 20 errors, I don't know what references I need but I am currently just opening visual studios and building the source.  (All the errors listed below)

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'pugixml\src\pugixml.hpp': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Scripting\TimecycleModification.cpp	20	
Error	C1083	Cannot open source file: '..\external\pugixml\src\pugixml.cpp': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\c1xx	1	
Error	C1083	Cannot open include file: 'simpleini\SimpleIni.h': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Menu\MenuConfig.h	12	
Error	C1083	Cannot open include file: 'simpleini\SimpleIni.h': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Menu\MenuConfig.h	12	
Error	C1083	Cannot open include file: 'pugixml\src\pugixml.hpp': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Submenus\AnimalRiding.cpp	33	
Error	C1083	Cannot open include file: 'pugixml\src\pugixml.hpp': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Submenus\PedAnimation.cpp	36	
Error	C1083	Cannot open include file: 'pugixml\src\pugixml.hpp': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Submenus\PedComponentChanger.cpp	43	
Error	C1083	Cannot open include file: 'pugixml\src\pugixml.hpp': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Submenus\PedModelChanger.cpp	39	
Error	C1083	Cannot open include file: 'simpleini\SimpleIni.h': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Submenus\PedSpeech.cpp	27	
Error	C1083	Cannot open include file: 'simpleini\SimpleIni.h': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Menu\MenuConfig.h	12	
Error	C1083	Cannot open include file: 'pugixml/src/pugixml.hpp': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Submenus\Spooner\FavouritesManagement.cpp	25	
Error	C1083	Cannot open include file: 'pugixml/src/pugixml.hpp': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Submenus\Spooner\FileManagement.cpp	51	
Error	C1083	Cannot open include file: 'pugixml\src\pugixml.hpp': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Submenus\Spooner\STSTask.cpp	22	
Error	C1083	Cannot open include file: 'pugixml\src\pugixml.hpp': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Submenus\Spooner\STSTasks.cpp	34	
Error	C1083	Cannot open include file: 'pugixml/src/pugixml.hpp': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Submenus\Spooner\Submenus.cpp	63	
Error	C1083	Cannot open include file: 'pugixml\src\pugixml.hpp': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Submenus\Teleport\Teleport_Submenus.cpp	31	
Error	C1083	Cannot open include file: 'pugixml\src\pugixml.hpp': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Submenus\VehicleSpawner.cpp	45	
Error	C1083	Cannot open include file: 'pugixml\src\pugixml.hpp': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Submenus\WeaponOptions.cpp	51	
Error	C1083	Cannot open include file: 'dirent\include\dirent.h': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Util\ExePath.cpp	16	
Error	C1083	Cannot open include file: 'pugixml\src\pugixml.hpp': No such file or directory	Menyoo	C:\Users\MYNAME\Desktop\1MenyooSP-1.4.0\Solution\source\Scripting\ModelNames.cpp	27

**Comment by Sainan** [comment]
You can press the "Close" button on this issue.
