### ISSUE TITLE
Chinese text render issue.

### ISSUE THREAD

**Issue by heroboy** [MAFINS/MenyooSP#174]
![image](https://user-images.githubusercontent.com/54468/97807715-61bab000-1c9d-11eb-8be1-7331a78864db.png)
![image](https://user-images.githubusercontent.com/54468/97807721-6aab8180-1c9d-11eb-9dbf-5c5e0d716b88.png)
See the picture, title texts are rendering ok. But the all menu items are rendered as blank rect.

**Comment by heroboy** [comment]
sorry. I find I can fix this by change the font in setting.

**Comment by zz17635** [comment]
对于menyoo中某些地方强制显示中文字符而出现口口口的问题，在 settings --> menu fonts 中把 options 和 selected option 相应的字体设置都改成 pricedown 即可。

**Comment by BaseMax** [comment]
> sorry. I find I can fix this by change the font in setting.

Same issue, would you explain more?which settings? how can change font of the menu? @heroboy

**Comment by BaseMax** [comment]
> settings --> menu fonts

Ah, let me try... @zz17635
