### ISSUE TITLE
Crash game

### ISSUE THREAD

**Issue by VitorCorpYT** [MAFINS/MenyooSP#175]
My game is running on 1.0.2020.1 and the Menyoo is on 1.0.2020.0 please uptade!

**Comment by tbfr31** [comment]
Hi,

I guess that you are looking for Menyoo compatible with game version 1.0.2060.1, not 1.0.2020.1.

Unrealesd *.asi version 1.4.1 is available below:

[MenyooSP-v1.4.1.Unreleased.zip](https://github.com/MAFINS/MenyooSP/files/5578672/MenyooSP-v1.4.1.Unreleased.zip)

Note that the original dll *.asi was generated with VB 2017. I didn't identify any issue with VB 2019.

Hope that will help you.
