### ISSUE TITLE
menyoo trainer not working ver 1.52 latest

### ISSUE THREAD

**Issue by Faheemkhan1-droid** [MAFINS/MenyooSP#179]
Hey..
Today i'm update the game to latest then menyoo trainer is not working i'm trying to a lot of time but not someone is know about this ...

**Comment by metoxys** [comment]
Tested the previous update's release with current scripthookv and it worked fine on my end (albeit the "don't despawn new vehicles" bit was out of date)

Make sure that you're using the latest scripthookv

If that didn't work, post your scripthook and asiloader log files
