### ISSUE TITLE
Menyoo Customs: Offroad wheel list is split in a weird way

### ISSUE THREAD

**Issue by metoxys** [MAFINS/MenyooSP#183]
Most likely linked to #182 

"Stock Rims" goes up to ID 16 (chrome Dune Basher)
"Chrome Rims" starts from ID 17 (chrome Five Star) and goes up to ID 34 (Rugged Snowflake)

The IDs are as follows:  
0-9 (colored Raider to Mil Spec Steelie)  
10-19 (chrome Raider to Mil Spec Steelie)  
20-34 (colored Retro Steelie to Rugged Snowflake)

Correct ID ranges are 0-9, 20-34 for "Stock Rims" and 10-19 for "Chrome Rims"

**Comment by MAFINS** [comment]
Should the split just be removed and the wheel names uncategorised? Or should it be split in those correct ranges instead?
This is an old issue so I'm not sure if you or someone else addressed it already or not haha.

**Comment by metoxys** [comment]
> Should the split just be removed and the wheel names uncategorised? Or should it be split in those correct ranges instead?
> This is an old issue so I'm not sure if you or someone else addressed it already or not haha.

I'd split in correct ranges, also for the Open Wheel/Street/Track tires with the 6 different tire designs

I was going to try and do it but I didn't have the time yet

**Comment by metoxys** [comment]
Closing as this is no longer the case in the current version
