### ISSUE TITLE
Regarding Kosatka Submarine in Story Mode

### ISSUE THREAD

**Issue by Sam071100** [MAFINS/MenyooSP#184]
Not able to drive the Kosatka Submarine or the new cayo Perico heist vehicles in GTA V's story mode. As I am selecting the Kosatka Submarine under the boat section of the Menyoo trainer the huge submarine appears but only for a few seconds and then disappears and the characters come on his foot. Please fix this issue ASAP. I am presently using the v1.0.2189.0 of Script Hook V which was released on 18th December.

**Comment by Anoxmous24** [comment]
I thought it was just me but the issue does need to be fixed with an update of Menyoo.
