### ISSUE TITLE
Crash when trying to delete vehicles

### ISSUE THREAD

**Issue by martuksxxxx** [MAFINS/MenyooSP#21]
When playing on FiveM (dont know if this problem occurs on SP), but when you try to delete a vehicle using spooner (using remove vehicles in proximity also), game just crashes, while deleteing objects and peds goes smoothly

**Comment by MAFINS** [comment]
could you check if it happens in sp too?

**Comment by martuksxxxx** [comment]
I will, I will reply to you in 20 hours (when I get home and check), thank
you for taking an interest in this issue.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2019-03-17, sk, 18:54 MAFINS <notifications@github.com> rašė:

**Comment by martuksxxxx** [comment]
I just checked this trainer in FiveM singleplayer and in there you can
delete all the cars you want with no problems and with no crashing. It only
crashes when deleting cars in FiveM (only cars, deleting peds and objects
works fine)
Can you confirm you got this email?

2019-03-17, sk, 18:54 MAFINS <notifications@github.com> rašė:

**Comment by Disquse** [comment]
Probably this issue is caused by the FiveM built in anticheat which not work in FiveM SP btw. Some people reported such issues even on other trainers. You need to contact the FiveM developers via forums to resolve this.

**Comment by MAFINS** [comment]
I'm afraid I cannot rectify the issue directly as I have no information on the causes, and since I am no longer developing with such potency anyway.

I'll keep this issue open if anyone can help.

**Comment by martuksxxxx** [comment]
Thank you. I have found one person who doesnt seem to have such problem, I
was thinking maybe it is related to me editing config file. Hoever only
things that I have edited to my knowledge are keybindings. Or it might be
incompatibility issues between different trainers installed. I dont know.

2019-03-20, tr, 20:38 MAFINS <notifications@github.com> rašė:

**Comment by badphaze** [comment]
on my local server at me does not crash only at my friend the game crash
