### ISSUE TITLE
Why is not updated.

### ISSUE THREAD

**Issue by ZatarraTR** [MAFINS/MenyooSP#215]
Dude did you quit developing?
If not, please update..
I love it and want it to be up to date.
Official update is essential to use it without problems..

**Comment by frafflg** [comment]
wow , great points , actually i was kinda ready to read some messages of the usual spiteful people who yell at those who rightly ask for a problem to be solved ahah , very glad that you specified all that , also did you noticed my long report of bugs ? it is the one right after this post you make
