### ISSUE TITLE
No DLC cars appear in spawn vehicle box

### ISSUE THREAD

**Issue by modzz1997** [MAFINS/MenyooSP#218]
After a reinstall of gta no gta online cars, nor add-on ones appear in "spawn vehicle" box. Also, none of my previous menyoo features work, i want to spawn my weapon loadouts, but after I click on them, game crashes or no weapons apply. Please help, this issue is slowly driving me insane.

**Comment by PulledResort** [comment]
> After a reinstall of gta no gta online cars, nor add-on ones appear in "spawn vehicle" box. Also, none of my previous menyoo features work, i want to spawn my weapon loadouts, but after I click on them, game crashes or no weapons apply. Please help, this issue is slowly driving me insane.
![image](https://user-images.githubusercontent.com/76795823/108611290-51912280-73ab-11eb-9245-a36587b08a0c.png)

**Comment by modzz1997** [comment]
My VehicleList.xml remains unedited in MenyooStuff folder. As I understand, i have to put my GTA V root folder to Rockstar Games directory to make it work. I'm just going to mention, that after 1.0.2215.0 ScriptHook update, Menyoo was working for me like 5-6 days without being in Rockstar Games folder, after that i had to reinstall my gta v, and my dlcs stopped working right after reinstall.

**Comment by modzz1997** [comment]
> > After a reinstall of gta no gta online cars, nor add-on ones appear in "spawn vehicle" box. Also, none of my previous menyoo features work, i want to spawn my weapon loadouts, but after I click on them, game crashes or no weapons apply. Please help, this issue is slowly driving me insane.
> > ![image](https://user-images.githubusercontent.com/76795823/108611290-51912280-73ab-11eb-9245-a36587b08a0c.png)
> 
> Edit: Also make sure you have VehicleList.xml inside your menyooStuff folder. (If you don't have all the vehicles download this VehicleList.xml)
> [5c3ddf8](https://github.com/MAFINS/MenyooSP/commit/5c3ddf8573ba9b84a85530a4b2a25681c5cc4a0a)

My VehicleList.xml remains unedited in MenyooStuff folder. As I understand, i have to put my GTA V root folder to Rockstar Games directory to make it work. I'm just going to mention, that after 1.0.2215.0 ScriptHook update, Menyoo was working for me like 5-6 days without being in Rockstar Games folder, after that i had to reinstall my gta v, and my dlcs stopped working right after reinstall.

**Comment by frafflg** [comment]
is pretty clear that this trainer really need an update

**Comment by Leve1** [comment]
> is pretty clear that this trainer really need an update

Here's link to latest build https://ci.appveyor.com/api/buildjobs/eyrsnq7pb1p3fe1f/artifacts/MenyooSP.zip
Its updated to latest version

**Comment by frafflg** [comment]
> 
> 
> > is pretty clear that this trainer really need an update
> 
> Here's link to latest build https://ci.appveyor.com/api/buildjobs/eyrsnq7pb1p3fe1f/artifacts/MenyooSP.zip
> Its updated to latest version

it is very strange , why put that link there and not here in this page of github ? , what is the official very first site were mafins publish the latest version of this trainer everytime ?

**Comment by frafflg** [comment]
> 
> 
> > is pretty clear that this trainer really need an update
> 
> Here's link to latest build https://ci.appveyor.com/api/buildjobs/eyrsnq7pb1p3fe1f/artifacts/MenyooSP.zip
> Its updated to latest version

it is the same trainer that mafins released in 2020 that have all the issues that people reported , me included , you clearly are kidding me , go fak yourself , asshole

**Comment by Leve1** [comment]
> > > is pretty clear that this trainer really need an update
> > 
> > 
> > Here's link to latest build https://ci.appveyor.com/api/buildjobs/eyrsnq7pb1p3fe1f/artifacts/MenyooSP.zip
> > Its updated to latest version
> 
> it is the same trainer that mafins released in 2020 that have all the issues that people reported , me included , you clearly are kidding me , go fak yourself , asshole

It literally has the updated online vehicle bypass which fixes vehicles disappearing, latest cayo perocio weapons,  vehicles and ped list's, and its working fine for me.

**Comment by frafflg** [comment]
> 
> 
> > > > is pretty clear that this trainer really need an update
> > > 
> > > 
> > > Here's link to latest build https://ci.appveyor.com/api/buildjobs/eyrsnq7pb1p3fe1f/artifacts/MenyooSP.zip
> > > Its updated to latest version
> > 
> > 
> > it is the same trainer that mafins released in 2020 that have all the issues that people reported , me included , you clearly are kidding me , go fak yourself , asshole
> 
> It literally has the updated online vehicle bypass which fixes vehicles disappearing, latest cayo perocio weapons, vehicles and ped list's, and its working fine for me.

i don't care,  it isn't working
