### ISSUE TITLE
Mafins you did wrong...!!!!

### ISSUE THREAD

**Issue by ZatarraTR** [MAFINS/MenyooSP#230]
Why did you delete the topic? Did it bother you to say the truth? Did you become a man when the subject was erased?

**Comment by ReadyP1ayerTwo** [comment]
> Why did you delete the topic? Did it bother you to say the truth? Did you become a man when the subject was erased?

Imagine telling people **to kill themselves** just because they told you mafins doesn't update the menu anymore. You truly are a mental case, aren't you? Enjoy your report.

**Comment by ReadyP1ayerTwo** [comment]
> Why did you delete the topic? Did it bother you to say the truth? Did you become a man when the subject was erased?

https://www.youtube.com/watch?v=H5d42w4ZcY4

**Comment by ToxxicFuse** [comment]
> Why did you delete the topic? Did it bother you to say the truth? Did you become a man when the subject was erased?

Please leave kiddo, a lot of the stuff you guys are complaining about is happening because you didn't install the trainer correctly

**Comment by ZatarraTR** [comment]
> > Why did you delete the topic? Did it bother you to say the truth? Did you become a man when the subject was erased?
> 
> Imagine telling people **to kill themselves** just because they told you mafins doesn't update the menu anymore. You truly are a mental case, aren't you? Enjoy your report.

**I doubt you are human.
Your adjective does not look like a human.**

**Comment by ZatarraTR** [comment]
> > Why did you delete the topic? Did it bother you to say the truth? Did you become a man when the subject was erased?
> 
> Please leave kiddo, a lot of the stuff you guys are complaining about is caused by not install the trainer correctly

**You have not been asked your opinion ..
I don't need mind.**

**Comment by ToxxicFuse** [comment]
@MAFINS Could you please close this issue since it's nonsense and block these clowns? ❤️
_(ZatarraTR and frafflg)_

**Comment by ZatarraTR** [comment]
> @MAFINS Could you please close this issue since it's nonsense and block these clowns? ❤️
> _(ZatarraTR and frafflg)_

I didn't ask your name but...
You said it yourself :)
**Silly clown** 💯

**Comment by frafflg** [comment]
> 
> 
> > > Why did you delete the topic? Did it bother you to say the truth? Did you become a man when the subject was erased?
> > 
> > 
> > Please leave kiddo, a lot of the stuff you guys are complaining about is caused by not install the trainer correctly
> 
> **You have not been asked your opinion .. I don't need mind.**

hei , just block those dick heads , we made our points with them , no need to waste any more time arguing with them , and yes mafins need to stop begin like those shit heads who literally care to interact only when they are insulted , but hey , we keep doing this , since it is the only thing he seem to understand , i have opened a new issue only to reply to him , it will be closed soon but at least he will read it
