### ISSUE TITLE
mafins can you please go fuck yourself ? you are evne more insulting that those two assholes 

### ISSUE THREAD

**Issue by frafflg** [MAFINS/MenyooSP#231]
"These issues seem to be mentioned in issue thread #214
Hopefully someone can address them" are you fucking kidding me ? I ACTUALLY REPORTED THOSE PROBLEMS , I FUCKING ADDRESSED THEM SOME HOURS AGO , THERE ISN'T ANY NEED TO HOPE FOR SOMEONE ELSE TO DO IT , AND AGAIN , YOU ASKED FOR IT , BE HONEST , SINCE WHEN PEOPLE ARE REPORTING ISSUES REGARDING THE LUCK OF UPDATES ?? SINCE FUCKING WHEN ??? SINCE FUCKING 2019 , BUT YOU NEVER FUCKING CARE ABOUT SOLVE THEM , AND ALL OF THE SUDDEN , NOW THAT SOMEONE IS GETTING MORE AGGRESSIVE YOU SUDDENLY SHOW UP , IF YOU WANT US TO BE RESPECTFUL THEN YOU WILL CARE ABOUT FUCKING REPLY AND SOLVE THOSE BUGS WITHOUT ANY NEED TO BE RUDE , OTHERWISE YOU ARE FUCKING ASKING FOR THEM , ESPECIALLY CONSIDERING THAT I WAS FUCKING SURE THAT YOU NEVER REPLIED OR INTERACTED IN ANY WAY BECAUSE YOU NEVER WERE ONLINE IN THIS PAGE , BUT NOOOOO , YOU ARE ONLINE HERE , BUT SINCE NONE INSULTED YOU , YOU DIDN'T HAD ANY GOOD REASON TO EVEN FUCKING REPLY , FUCK YOU

**Comment by Disquse** [comment]
@MAFINS just ban him already :\

**Comment by frafflg** [comment]
> 
> 
> @MAFINS just ban him already :\

as i said you fucking dick , ignore the reports unless someone start insult everything is actually the reason why i have to behave in this way , got it you shit ? if you idiots were more respectful and care about update this wonderful trainer there weren't any need to do this , so instead of complain know that you just asked for it and fucking ban yourself from existence,  in other words , go fucking kill yourself , retarded shit , it may be incredible for you , but , when people ignore you on purpose , not giving a fuck about you , showing up only to argue and insult or to expect you to give the right when they say that they don't give a damn about you , well this don't help at all to be gentle , on the contrary , understood you shit ? don't want any insults ?? fucking be respectful or pay the consequences , none have to be banned except the shits who dared to tell us that we should shut up and accept how this trainer is supposed to be abandoned , dick

**Comment by frafflg** [comment]
> 
> 
> @MAFINS just ban him already :\

i mean seriously , you think it is normal to act like this ? create something and a some fucking point just acting like a lunatic idiot who get supported by dicks who claim that we should accept how all of the sudden someone decided to not update something that work so well and give so much satisfaction ?? if you think that this is normal then no wonder that you believe i am wrong , before complain for the insults fucking get why they occurred in the first place,  i was polite and respectful before those two shits had the nerve to tell us that we should just accept how this trainer suddenly not received any more fix and any more updates , they were disrespectful , then we were disrespectful , fuck you

**Comment by sadboilogan** [comment]
if you have such a problem about it, why dont you try fix it yourself? just because someone created a repo doesnt mean they need to deal with keeping such up to date, GitHub is designed to allow for other people help contribute, so why not do that instead of getting so mad, maybe he just doesnt have time for it? not a big deal.

**Comment by frafflg** [comment]
> 
> 
> @MAFINS just ban him already :\

here is an example, since you are so against this attitude , did you ever give a fuck about the fact that kindness must be mutual ? ever considered that instead of act like a dick or a moron and then be all surprised because people react in a rude way , wake up please , you are not the only one who want to be respected , and no , tell us even without bad words that with this luck of updates and fixes we should just suck it up ISN'T respectful at all , even if they tell it in a calm way , dick

**Comment by frafflg** [comment]
> 
> 
> if you have such a problem about it, why dont you try fix it yourself? just because someone created a repo doesnt mean they need to deal with keeping such up to date, GitHub is designed to allow for other people help contribute, so why not do that instead of getting so mad, maybe he just doesnt have time for it? not a big deal.

again with that bullshit ? no you retarded shit i won't fix anything , if i could i would have already done it you dick , also i am not the one who created this trainer and mafins is more than capable to do it , he just need to give a fuck since updates or not he is always online here , fucking moron , also no is not normal or acceptable to just be careless and let people with a problem , asshole

**Comment by CptLeetsy** [comment]
> kindness must be mutual ?

> you are not the only one who want to be respected

You were never kind to anyone. and respect has to be earned. But since you're acting like a spoon fed moron, you will never earn respect from anyone here.

People here are not at your (or anyone's) service. grow out of your parent's basement, if you want something, either you stay patient, either you do it yourself. 
That's how GitHub works, and how life works with strangers.  I still can't believe how you think you're oh so right, when you're wrong on every levels.

Also harasing people won't make them do anything for you, hope you can realize that. 
Asking people to kill themself is not either a way to make things go forward.

I strongly wish you get banned, either from GitHub or this repo. And that you stay stuck as long as possible with a broken trainer/game.  Because for the most, the trainer works perfectly fine :)

**Comment by frafflg** [comment]
> 
> 
> > kindness must be mutual ?
> 
> > you are not the only one who want to be respected
> 
> You were never kind to anyone. and respect has to be earned. But since you're acting like a spoon fed moron, you will never earn respect from anyone here.
> 
> People here are not at your (or anyone's) service. grow out of your parent's basement, if you want something, either you stay patient, either you do it yourself.
> That's how GitHub works, and how life works with strangers. I still can't believe how you think you're oh so right, when you're wrong on every levels.
> 
> Also harasing people won't make them do anything for you, hope you can realize that.
> Asking people to kill themself is not either a way to make things go forward.
> 
> I strongly wish you get banned, either from GitHub or this repo. And that you stay stuck as long as possible with a broken trainer/game. Because for the most, the trainer works perfectly fine :)

shut up dick everything you said is wrong , i am right , fuck you

**Comment by AvarianKnight** [comment]
> shut up dick everything you said is wrong , i am right , fuck you

Hmmm, I think roles are reversed here 🤔.

Stop being entitled, learn how to code, and do it yourself, or shut the fuck up, go cry a river, and learn to respect people.

**Comment by frafflg** [comment]
> 
> 
> > shut up dick everything you said is wrong , i am right , fuck you
> 
> Hmmm, I think roles are reversed here 🤔.
> 
> Stop being entitled, learn how to code, and do it yourself, or shut the fuck up, go cry a river, and learn to respect people.

reversed my fucking ass , no fucking updating or fixing of any kind , showing up only to close the posts were people reply ONLY when someone is insulting, instead of fucking complain be mindful and realize that all this rudeness and insults are the only fucking thing who managed to make you reply to the fucking posts , the only damn thing who make mafins show up damn it , before this everything were pretty much ignored just like none were really even online besides those people who publish the bugs , so in short you all bunch of dicks asked for it , again , some people are so fucking idiotic and stupid that they ignore when people are polite and respectful , then show up when they are provoked and have the fucking nerve to complain for them , just make peace with the brain please

**Comment by AvarianKnight** [comment]
The funny part is you think you're resolving anything with your shitty attitude, which also directly violates [GitHub community guidelines](https://docs.github.com/articles/github-community-guidelines).

The only thing you've gotten out of this is likely a ban from being able to do anything in this repository, with gaining nothing.

Projects are open source for a reason, contribute, or don't cry that things aren't working you entitled brat.

Anyways please enjoy the rest of your stay, as you will likely be banned from GitHub by the end of this.

**Comment by frafflg** [comment]
> 
> 
> The funny part is you think you're resolving anything with your shitty attitude, which also directly violates [GitHub community guidelines](https://docs.github.com/articles/github-community-guidelines).
> 
> The only thing you've gotten out of this is likely a ban from being able to do anything in this repository, with gaining nothing.
> 
> Projects are open source for a reason, contribute, or don't cry that things aren't working you entitled brat.
> 
> Anyways please enjoy the rest of your stay, as you will likely be banned from GitHub by the end of this.

as i have already said you retarded shit , be all polite and careful only caused everyone to ignore everyone , and as you can tell from your reaction , even if appearently you don't accept this attitude , you still only react to insults while if wasn't for them you probably would be one of those that ignore everything that get told , fucking asshole , another demonstration about how you asked for it , you are the one with a shitty attitude

**Comment by MAFINS** [comment]
> 
> 
> "These issues seem to be mentioned in issue thread #214
> Hopefully someone can address them" are you fucking kidding me ? I ACTUALLY REPORTED THOSE PROBLEMS , I FUCKING ADDRESSED THEM SOME HOURS AGO , THERE ISN'T ANY NEED TO HOPE FOR SOMEONE ELSE TO DO IT , AND AGAIN , YOU ASKED FOR IT , BE HONEST , SINCE WHEN PEOPLE ARE REPORTING ISSUES REGARDING THE LUCK OF UPDATES ?? SINCE FUCKING WHEN ??? SINCE FUCKING 2019 , BUT YOU NEVER FUCKING CARE ABOUT SOLVE THEM , AND ALL OF THE SUDDEN , NOW THAT SOMEONE IS GETTING MORE AGGRESSIVE YOU SUDDENLY SHOW UP , IF YOU WANT US TO BE RESPECTFUL THEN YOU WILL CARE ABOUT FUCKING REPLY AND SOLVE THOSE BUGS WITHOUT ANY NEED TO BE RUDE , OTHERWISE YOU ARE FUCKING ASKING FOR THEM , ESPECIALLY CONSIDERING THAT I WAS FUCKING SURE THAT YOU NEVER REPLIED OR INTERACTED IN ANY WAY BECAUSE YOU NEVER WERE ONLINE IN THIS PAGE , BUT NOOOOO , YOU ARE ONLINE HERE , BUT SINCE NONE INSULTED YOU , YOU DIDN'T HAD ANY GOOD REASON TO EVEN FUCKING REPLY , FUCK YOU

You can address them in your fork and make a pull request if you'd like.
Also, be civil. Profanity will not be tolerated. I'm not showing up because someone is aggressive. I'm showing up because these hate comments do not belong in the Issues of this repo. Actual enhancements and bug reports are welcome. Any more long hateful paragraphs of no real substance will warrant a ban in the future. Thank you.
