### ISSUE TITLE
Change License Plate?

### ISSUE THREAD

**Issue by poonasor** [MAFINS/MenyooSP#232]
Is there a way for me to change the license plate when I spawn cars in menyoo?

**Comment by CptLeetsy** [comment]
After spawning the car you desire, go in "Menyoo Customs" (located in the vehicles menu, right below vehicle spawner)
That tab allows you to modify your car, at the bottom of it, there's "PLATE TYPE", allowing you to choose between the different plate colors (press left or right to change it) 

Then below it you have "CUSTOMIZE LICENSE PLATE", which allows you to put any text you desire (as long as they fit)
press enter on it, it'll open you a submenu in the middle of the screen, type what you want, then press enter again and it will apply it to the plate.
