### ISSUE TITLE
Menyoo wont let me open my phone or even save

### ISSUE THREAD

**Issue by Toastyisback** [MAFINS/MenyooSP#236]
Hi I was just casually modding my GTA V game after not playing it for a really long time and updated the Menyoo mod, it worked fine for the first couple hours of gameplay and everything seemed fine, until I went to try to open my phone. I found out that I couldnt open my phone and when I tried to see if it was a keybinding issue I opened my pause menu to a infinite loading screen. At first i didnt think it was menyoo but then I got rid of it and the game worked as good as new, and i was able to open my phone and pause menu with no issues. I really like menyoo alot and dont want to have to use a different trainer, so pleae fi you can fix this quickly :)

**Comment by Toastyisback** [comment]
ok i have actually found out that it is not menyoo's fault for the phone but still does long loading screens on the pause menu

**Comment by ToxxicFuse** [comment]
> 
> 
> ok i have actually found out that it is not menyoo's fault for the phone but still does long loading screens on the pause menu

So the phone and save issue is solved?

Are you having the pause menu loading time issue without menyoo as well?

**Comment by Toastyisback** [comment]
Sorry for the confusion I forgot to post that it turns out it wasn’t
menyoos fault at all! It was a completely different mod that would screw
all other mods up!
