### ISSUE TITLE
Meenyoo is not updated

### ISSUE THREAD

**Issue by KingArthur1910** [MAFINS/MenyooSP#237]
I cannot find 3 guns in menyoo trainer which cam with cayo perico update including perico pistol, military rifle, combat shotgun

**Comment by dylan1114** [comment]
Tip: you can spawn such things by manually entering the name of the object in the files. Combat shotgun for example is **pumpshotgunh4** 

Most of the filenames can be found on the GTA Fandom website, under the **Miscellaneous Information** tab on the right side of the apge.
