### ISSUE TITLE
Can't add a Vehicle to my Favourite Vehicles

### ISSUE THREAD

**Issue by ELI-PLAY** [MAFINS/MenyooSP#241]
If I want to add a Vehicle like the 811 to my Favourites it doesn't show up. It always jumps from 0/0 -  1/0 and back.

**Comment by ToxxicFuse** [comment]
> 
> 
> If I want to add a Vehicle like the 811 to my Favourites it doesn't show up. It always jumps from 0/0 - 1/0 and back.

Slow answer, but do you have the menyooStuff folder inside your gta directory?

**Comment by ELI-PLAY** [comment]
Yes, I do

**Comment by ToxxicFuse** [comment]
> 
> 
> Yes, I do

Is the _Vehicle_ folder inside the _menyooStuff_ folder empty?

**Comment by MAFINS** [comment]
Confirm if a AddedVehicleModels.xml file has been created in your MenyooStuff folder. A solution may be to give yourself write access to the MenyooStuff folder by unchecking read-only in its properties.

**Comment by ELI-PLAY** [comment]
Thank you for helping me. I had to grant read access
