### ISSUE TITLE
Menyoo stops working after oufit change to a copied MP character

### ISSUE THREAD

**Issue by G0LDENGUN** [MAFINS/MenyooSP#248]
My issue is that menyoo stops working after that I want to change the oufit of my second or third MP character. GTA still works, but I can't press F8 after the "crash". A border pops up to say that there is an problem with "menyoo.asi" and different codes.. ( 37,36,33) As I know, my mods are updated. It would be great if someone could help me with this :)

**Comment by MAFINS** [comment]
Also mentioned in #249 
Hopefully someone can fix it soon
