### ISSUE TITLE
Menyoo doesn't save outfit to file and bugged object spooner

### ISSUE THREAD

**Issue by KaVVaski** [MAFINS/MenyooSP#251]
Hi. I have 2 bugs - when I want to save my outfit menyoo sends a notification that it has succeeded, but file is not created and when I want to catch my character in object spooner character falls down and can't be caught again, I have to restart the game

**Comment by KaVVaski** [comment]
i have to open game with admin permissions and i can save outfit, but catching character with object spooner still not working
https://streamable.com/0duqeh

**Comment by MAFINS** [comment]
Try unchecking 'Read-only' in the menyooStuff folder's properties.
