### ISSUE TITLE
Mod menu menyoo gta 5

### ISSUE THREAD

**Issue by Killervale007** [MAFINS/MenyooSP#255]
salve dall'ultima patch il i file del mod menu quando sono nei file di gioco il gioco non parte.
trovate un rimedio grazzie <3

**Comment by CptLeetsy** [comment]
If the game doesnt start it's linked to ScriptHook not being updated yet. Wait for it to be updated and your game should start just fine. 
( link here : http://www.dev-c.com/gtav/scripthookv/ )

If you downgraded your game to a previous version and it suddenly doesnt start anymore, it means you mess up something.
