### ISSUE TITLE
Vehicles Disappearing Instant

### ISSUE THREAD

**Issue by FySchii** [MAFINS/MenyooSP#256]
I have a problem with the Cars out of online mode, there despawn after like 5 seconds! 
I didnt found a solution yet, pls help.

**Comment by tbfr31** [comment]
A possible reason is that the version of MenyooSP that you are using is based on game version 1.0.2245.0 BUT you have updated the game to 1.0.2372.0.
MenyooSP has not been updated to 1.0.2372.0 so I don't see straight forward solution.

**Comment by ReadyP1ayerTwo** [comment]
> A possible reason is that the version of MenyooSP that you are using is based on game version 1.0.2245.0 BUT you have updated the game to 1.0.2372.0.
> MenyooSP has not been updated to 1.0.2372.0 so I don't see straight forward solution.

I figure the only solution is to wait for it to update. In my case; I can't use it whatsoever on FiveM because i've pushed my FiveM server version to the current GTA version.
