### ISSUE TITLE
MenyooSP not compatible with patch 1.0.2372.0

### ISSUE THREAD

**Issue by tbfr31** [MAFINS/MenyooSP#257]
New DCL vehicles have been added. That's great!
Please would it be possible to update the MenyooSP project such as to be compatible with the patch 1.0.2372.0?

**Comment by tbfr31** [comment]
Patch 1.0.2372 was added to enum eGameVersin in main.h. That's cool! Thanks.
Unfortunately, new DLC cars still can’t be used. If I pawn a Dominator GTT in the game the car instantaneously disappears.
I suspect the game versions not listed into the function EnableBlockedMpVehiclesInSp to be the cause of this issue (GTAmemoty.cpp). Unfortunately I cannot find the suitable value to add for game version 2372.

**Comment by MAFINS** [comment]
Well it's a global variable in shopController.ysc that has to be set to 1, last I recall.
Someone with the game would have to find its new id.

**Comment by iiKraze** [comment]
funny thing is i'm using 1.4.0 with the latest release of GTA perfectly fine and all the new cars show up fine. so ttheoretically no update its really needed

**Comment by ReadyP1ayerTwo** [comment]
> funny thing is i'm using 1.4.0 with the latest release of GTA perfectly fine and all the new cars show up fine. so theoretically no update its really needed

Still a good thing to update it though regardless. As far as i know FiveM isn't really supported; Or at least FiveM doesn't go out of their way to keep these mods compatible with FiveM.. Maybe some of the people that keep menyoo updated DO; But anyways It needs to be updated to work with FiveM. They recently changed how scripthook mods hook into their client or something alike and now all client sided mods are going to need to be updated to work on their client. I'd have to look up what exactly it is that they said but right now i'm about to take off and i won't be back for at least a couple hours.

**Comment by SmokeyCheetah** [comment]
Unfortunately, same for me, Menyoo was my favourite "mapping" modmenu on my localhost, now I can't run it 😕 I hope update will be released soon 😄

**Comment by ReadyP1ayerTwo** [comment]
> Unfortunately, same for me, Menyoo was my favourite "mapping" modmenu on my localhost, now I can't run it 😕 I hope update will be released soon 😄 (FiveM)

if you stop enforcing DLC it SHOULD work... For now. Good luck, friend :)

**Comment by SmokeyCheetah** [comment]
> > Unfortunately, same for me, Menyoo was my favourite "mapping" modmenu on my localhost, now I can't run it 😕 I hope update will be released soon 😄 (FiveM)
> 
> if you stop enforcing DLC it SHOULD work... For now. Good luck, friend :)

What do you mean by "enforcing DLC" ? 😄

**Comment by RiKiThEBrO** [comment]
To fix menyoo you need a new global and hash-map for veh spawn and model requests

**Comment by SmokeyCheetah** [comment]
> To fix menyoo you need a new global and hash-map for veh spawn and model requests

Oh, I don't understand that things :D Soo... I will try to wait.

**Comment by iiKraze** [comment]
there was a new release on appveyor 2 days ago which updated the vehicle/peds/object lists from what i can see

**Comment by ReadyP1ayerTwo** [comment]
> > > Unfortunately, same for me, Menyoo was my favourite "mapping" modmenu on my localhost, now I can't run it 😕 I hope update will be released soon 😄 (FiveM)
> > 
> > 
> > if you stop enforcing DLC it SHOULD work... For now. Good luck, friend :)
> 
> What do you mean by "enforcing DLC" ? 😄

Honestly if you don't understand what i'm saying.. you probably aren't enforcing DLC to your server.

**Regardless though; what i mean by enforcing DLC is** To use the tuners DLC you have to put **+sv_enforceGameBuild tuner** into your server starter .bat file

**Comment by SmokeyCheetah** [comment]
Oh, if you mean that, I use normal version before tuner, and Menyoo doesn't work... problem is FiveM changed probably code how to reach plugins and Menyoo is not compatible then.
