### ISSUE TITLE
Menyoo Crashes When Teleporting

### ISSUE THREAD

**Issue by D1Drxco** [MAFINS/MenyooSP#265]
Basically, whenever I try to teleport into an interior, like the Low-End Apartment, for example, this happens:
![unknown (1)](https://user-images.githubusercontent.com/88579275/128596408-e7af6edd-3126-4141-ba61-74e19e9922f3.png)

Whenever I load into a saved game, it fixes my Menyoo, but my entire game CRASHES when I try to teleport into an online interior. Is there any way to fix this?

**Comment by MAFINS** [comment]
Last I remember, this used to be caused by using an outdated modded gameconfig file.
Try using a fresh one. Feel free to re-open the issue if this persists.
