### ISSUE TITLE
Crash on new update

### ISSUE THREAD

**Issue by Hazmi35** [MAFINS/MenyooSP#28]
OS: Windows 10 1903
GTA V Version: 1.0.1737.0
Steam: Yes
Script Hook V Version: v1.0.1737.0
Menyoo Version: 1.0.1
Details:
Launching GTA V causes a never-ending load sequence for a few minutes and then crashes.

**Comment by ProgrammingHider** [comment]
Your GTA Version is Old, Update to 1737.0, maybe it will work.

**Comment by Hazmi35** [comment]
Ooops wrong version I mean 1.0.1737.0

**Comment by ProgrammingHider** [comment]
Yeah I'm Also Crashing on 1737, but Using Windows 8.1 lol

**Comment by Hazmi35** [comment]
I guess what OS you're using doesn't matter

**Comment by Hazmi35** [comment]
I guess what OS you're in doesn't matter.

**Comment by MAFINS** [comment]
Oh no
Why do they still update this game smh.
Sorry, I won't be updating anything unfortunately. Feel free to update yourself, though. I can approve pull requests.

**Comment by Hazmi35** [comment]
Welp, I need to learn C++ fast 😂

**Comment by Hazmi35** [comment]
I heard that downgrading menyoo from version 1.0.1 to version 1.0.0 fixes this problem, but VehicleList.xml and PropList.xml needs to be updated

**Comment by Hazmi35** [comment]
> Oh no
> Why do they still update this game smh.
> Sorry, I won't be updating anything unfortunately. Feel free to update yourself, though. I can approve pull requests.

Are you discontinuing menyoo, or just pausing its development?

**Comment by Malogna** [comment]
> I heard that downgrading menyoo from version 1.0.1 to version 1.0.0 fixes this problem, but VehicleList.xml and PropList.xml needs to be updated

vehiclelist and proplist have been updated, check new commit from 3 days ago
