### ISSUE TITLE
Menyoo Outfits XML Crash on FiveM

### ISSUE THREAD

**Issue by WolfTM** [MAFINS/MenyooSP#293]
If you want to open an XML outfit with menyoo on fivem your game crashes.

[Screenshot](https://i.imgur.com/ehrWAhB.png)

For some reason it also does not save any logs/crash logs.
If I got one I will upload it here after.

**Comment by HumourNL** [comment]
I have found the fix. Go to Update.rpf/common/data/dlclist.xml. Uncomment or remove the following line.
`<Item>dlcpacks:/mpchristmas2018/</Item>`

This will stop the issue with spawning mp female and mp males.

**Comment by WolfTM** [comment]
> I have found the fix. Go to Update.rpf/common/data/dlclist.xml. Uncomment or remove the following line. `<Item>dlcpacks:/mpchristmas2018/</Item>`
> 
> This will stop the issue with spawning mp female and mp males.

You legend. Thanks.
#NL
