### ISSUE TITLE
MP Model Spawn

### ISSUE THREAD

**Issue by ootap** [MAFINS/MenyooSP#298]
When changing your model to the MP model it crashes. This doesn't happen on any other trainer I try, and it always crashes trying to pick MP model, no other model. It makes it literally unusable.

This only started happening on this most recent update, The Contract.

**Comment by Leeroy736** [comment]
I faced exactly the same problem as yours

**Comment by HumourNL** [comment]
I have found the fix. Go to Update.rpf/common/data/dlclist.xml. Uncomment or remove the following line.
`<Item>dlcpacks:/mpchristmas2018/</Item>`

This will stop the issue with spawning mp female and mp males.
