### ISSUE TITLE
Add Chameleon paint category

### ISSUE THREAD

**Issue by metoxys** [MAFINS/MenyooSP#303]
Feature request for the future

Apparently [the Contract DLC included a new category of paint](https://gtaforums.com/topic/978991-chameleon-paint/) that is being discovered. Not much info yet.

**Comment by itsjustcurtis** [comment]
Chameleon paints are currently listed under Chrome category. Worth noting for if R* does add a new paint category.

To add to this, the current paint selections are hardcoded to match the vanilla LS Customs colours. Whilst addon ID's can be selected in Menyoo, they cannot be picked by name in the list. Is it possible to have the list read from carmodcols in much the same way that tuning parts are? LS Customs correctly displays addon colours in all categories, there may be a way to copy that code across?

**Comment by metoxys** [comment]
> To add to this, the current paint selections are hardcoded to match the vanilla LS Customs colours. Whilst addon ID's can be selected in Menyoo, they cannot be picked by name in the list. Is it possible to have the list read from carmodcols in much the same way that wheels are? LS Customs correctly displays addon colours in all categories, there may be a way to copy that code across?
If I were you I'd open up a separate issue for this

**Comment by itsjustcurtis** [comment]
I felt it was related as the suggestion I have made would solve the issue as it currently stands, without needing a new category for the time being. All the chameleon paints are currently accessible, just not in list form.

**Comment by itsjustcurtis** [comment]
#314 now addresses this in the same way LSC does. Awaiting review by Mafins

**Comment by metoxys** [comment]
Done with #314
