### ISSUE TITLE
Cant use menyoo since new gta update

### ISSUE THREAD

**Issue by SignoreLuis** [MAFINS/MenyooSP#305]
Hey, I updated scripthookv for the new gta update. Since then when I want to select a freemode ped I get an error. 

CORE: An exceptition occured while executing 'Menyoo.asi'

[https://streamable.com/78bpfe](https://streamable.com/78bpfe)

**Comment by TayMcKenzieNZ** [comment]
download this fx_asi_build.res from the thread and apply it to Menyoo.asi and any other asi files

https://forum.cfx.re/t/simple-trainer-wont-show-up/4183132/12

**Comment by SignoreLuis** [comment]
Does this work for singleplayer too?

**Comment by TayMcKenzieNZ** [comment]
Should do, I can't see why not. Basically by doing this, we're telling the menyoo asi file to support cayo perico, los santos tuners, and the latest dlc.

**Comment by TayMcKenzieNZ** [comment]
However, ideally, the asi creator (in this case MAFINS) should be doing this every time Menyoo needs updating for a new dlc.

**Comment by SignoreLuis** [comment]
I am pressing my menyoo open hotkey and nothing happens

**Comment by TayMcKenzieNZ** [comment]
Yep, I've explained what you need to do.

**Comment by SignoreLuis** [comment]
i did everything, i applied it on every .asi file which is in my gta 5 root folder

**Comment by TayMcKenzieNZ** [comment]
You obviously haven't if you can type that fast...

You need to do exactly what it says here:

https://forum.cfx.re/t/simple-trainer-wont-show-up/4183132/12

However you need to download the latest fx_asi_build.res from here: https://forum.cfx.re/t/simple-trainer-wont-show-up/4183132/15

Or, be patient and wait for MAFINS or someone to do it. Clearly you can't follow simple instructions...

**Comment by SignoreLuis** [comment]
I did it with every .asi file 

enbfeeder.asi
HeapAdjuster.asi
Menyoo.asi
NativeTrainer.asi
openCameraV.asi
OpenIV.asi
PackfileLimitAdjuster.asi
QuantV.asi
SceneDirector.asi
ScriptHookVDotNet.asi
shadows.asi
timecyclemods.asi

And if i press my menyoo open key F12 (123) it wont open

**Comment by TayMcKenzieNZ** [comment]
> And if i press my menyoo open key F12 (123) it wont open

I had mine set to the ~ key just before the number 1 on my keyboard, however that opens the menu to enter cheats, and it would crash my game. Changing it back to F8, I haven't had any issue. Try this.

**Comment by SignoreLuis** [comment]
yes it work with f8 but it still dont fix my problem. if i am changing my ped to a freemode male or female ped (or using a outfit with the freemode ped) my game crashes "CORE: An exceptition occured while executing 'Menyoo.asi'"

**Comment by TayMcKenzieNZ** [comment]
You must have done something wrong then. I have no issues selecting freemode male or female, and then selecting a saved outfit in the wardrobe option, or cycling through the clothing items.

**Comment by SignoreLuis** [comment]
I did everything. Since the new gta update, my menyoo.asi isnt working

**Comment by kasuganosoras** [comment]
> You must have done something wrong then. I have no issues selecting freemode male or female, and then selecting a saved outfit in the wardrobe option, or cycling through the clothing items.

He is playing GTA V Single player, not FiveM. It may cause by some plugins conflict or ScriptHook native issue.

**Comment by SignoreLuis** [comment]
> > You must have done something wrong then. I have no issues selecting freemode male or female, and then selecting a saved outfit in the wardrobe option, or cycling through the clothing items.
> 
> He is playing GTA V Single player, not FiveM. It may cause by some plugins conflict or ScriptHook native error.
> 
> Add the special build number cannot solve this issue, it just makes you can run this trainer in FiveM.

Exactly.

**Comment by TayMcKenzieNZ** [comment]
Well I don't know what his problem is then, F8 works fine for me, I'm able to select Freeroam male or female, and yes I'm talking about single player too.

**Comment by GtaMods4You** [comment]
Try this: https://www.mediafire.com/file/1hrlq9v0hbzkaha/Menyoo_28-12-2021.zip/file

**Comment by SignoreLuis** [comment]
> Try this: https://www.mediafire.com/file/1hrlq9v0hbzkaha/Menyoo_28-12-2021.zip/file

No it down work for me

**Comment by SoulReaver-1981** [comment]
Are you still getting the same error..? does any of the other outfits work or is it just the one in your video..? also, it would be useful if you attached your ScriptHookV & asiloader .log files so we can see whats going on..

**Comment by AmazyCrazy** [comment]
Hey, would the this stuff work for the extended camera settings asi?  I tried and it didn't seem to work?

Thanks :)

**Comment by TayMcKenzieNZ** [comment]
> Hey, would the this stuff work for the extended camera settings asi? I tried and it didn't seem to work?
> 
> Thanks :)

I tried it also and no luck, though maybe we need to grab OpenIV's one?

**Comment by AmazyCrazy** [comment]
> > Hey, would the this stuff work for the extended camera settings asi? I tried and it didn't seem to work?
> > Thanks :)
> 
> I tried it also and no luck, though maybe we need to grab OpenIV's one?

What do you mean?  Also I had the same problem with menyoo as others so I downloaded a fix posted on here and now when applying a saved outfit I get the error but then the outfit loads just fine?

Thanks :)

**Comment by TayMcKenzieNZ** [comment]
🤷‍♂️ Just wait for MAFINS or someone to update it, idk why y'all having issues

**Comment by AmazyCrazy** [comment]
@TayMcKenzieNZ What did you mean by (grab OpenIV's one) and yes I agree I'm sure he is working on the fix as we speak :)

**Comment by SignoreLuis** [comment]
> Are you still getting the same error..? does any of the other outfits work or is it just the one in your video..? also, it would be useful if you attached your ScriptHookV & asiloader .log files so we can see whats going on..

Here my log from scripthookv and asiloader
[ScriptHookV.log](https://github.com/MAFINS/MenyooSP/files/7794886/ScriptHookV.log)
[asiloader.log](https://github.com/MAFINS/MenyooSP/files/7794887/asiloader.log)

**Comment by SoulReaver-1981** [comment]
@SignoreLuis - your problem is most likely another mod or menu is conflicting with menyoo. Try removing them all and see if your still having the same issues.. If everything's ok, then start re-enabling them one at a time untill you find the culprit.. (my guess is its that SceneDirector.asi you have installed)

**Comment by SoulReaver-1981** [comment]
> man_shrugging Just wait for MAFINS or someone to update it, idk why y'all having issues

I already updated it, including the latest FX_ASI_BUILD 2545 

Link: https://www.mediafire.com/file/1hrlq9v0hbzkaha/Menyoo_28-12-2021.zip/file

**Comment by MAFINS** [comment]
> @SignoreLuis 

Please refrain from posting links that don't follow the guidelines, thanks. You're welcome to make a fork or a pull request that follows the licence.

**Comment by mistahwolf** [comment]
> download this fx_asi_build.res from the thread and apply it to Menyoo.asi and any other asi files
> 
> https://forum.cfx.re/t/simple-trainer-wont-show-up/4183132/12

Hey, so I used this method to get Menyoo to load maps with high prop numbers again which it did fine before the $#!%%y 'contract dlc'. Previously, it was menyoo that would crash the game and it would show up as the cause when checking the scripthook log. After using this, everything loads in but now GTA craps the bed seconds after. Here's the error message that comes up. Anybody got an idea of how to fix this?

Faulting application name: GTA5.exe, version: 1.0.2612.1, time stamp: 0x625d7853
Faulting module name: KERNELBASE.dll, version: 6.1.7601.24441, time stamp: 0x5cb935a7
Exception code: 0xc0000005
Fault offset: 0x0000000000001b44
Faulting process id: 0x22f0
Faulting application start time: 0x01d863f43c996bb7
Faulting application path: D:\Grand Theft Auto V\GTA5.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
