### ISSUE TITLE
Menyoo dont work

### ISSUE THREAD

**Issue by Spherp** [MAFINS/MenyooSP#311]
I download the menyoo and the script and put menyoo stuff and menyoo.asi than scripthookv and dinput8 but it dont work

**Comment by PrO-GenGU** [comment]
same here

**Comment by The-UnXplained** [comment]
The last release on here was on the 15th Aug 2021.. Did you really expect it to still work..? pmsl

**Comment by SignoreLuis** [comment]
MENYOO SCRIPTHOOK FIX:
- delete mods folder (make backup from your mods)
- repair game (check for errors)
- https://www.gta5-mods.com/tools/heapadjuster
- https://www.gta5-mods.com/tools/packfile-limit-adjuster
• heap adjuster settings: HEAP_SIZE = 1750
• packfilelimitadjuster settings: packfile_list_size = 20000
• Install gameconfig https://www.gta5-mods.com/misc/gta-5-gameconfig-300-cars#comments_tab
• delete mpchristmas2018 from dlclist.xml

**Comment by The-UnXplained** [comment]
Updated version: https://www.mediafire.com/file/1hrlq9v0hbzkaha/Menyoo_28-12-2021.zip/file

**Comment by Maximismus** [comment]
Wie kann ich menyoo herunterladen?

**Comment by The-UnXplained** [comment]
> > The last release on here was on the 15th Aug 2021.. Did you really expect it to still work..? pmsl
> 
> Hah, smart. It's 8/3/2022 and it is still working perfectly on GTAV and also on FIVEM. Don't run mouth when unknowledged.

Kid, you clearly have no idea what you are even talking about.. for a start, the Game Version has to be updated in 'main.h' and 'GTAmemory.cpp' also has to be updated every time there's a new title update.. #dumbass

**Comment by adversaru** [comment]
> > > The last release on here was on the 15th Aug 2021.. Did you really expect it to still work..? pmsl
> > 
> > 
> > Hah, smart. It's 8/3/2022 and it is still working perfectly on GTAV and also on FIVEM. Don't run mouth when unknowledged.
> 
> Kid, you clearly have no idea what you are even talking about.. for a start, the Game Version has to be updated in 'main.h' and 'GTAmemory.cpp' also has to be updated every time there's a new title update.. #dumbass

Wow, you have to add 2 lines of code, such a hard work 😂😂😂
Matter of fact for yourself: atm the menu is updated and working on every version of FiveM.
I wont say it third time: don't run your mouth again when you're competely unknowledged. 🤝
