### ISSUE TITLE
Project not compiling (I'm new to this)

### ISSUE THREAD

**Issue by ShawnPR1** [MAFINS/MenyooSP#32]
This is most definitely on my side, but I have no other way to find out what I need to do or what I'm doing wrong.

I'm very new to the modding scene and don't even know where to start. Sorry for posting this here as an issue, but I cannot find any tutorial or even someone with some knowledge on how to build this solution and mine cannot build at all.

Steps I've taken to try and get coding on this phenomenal mod:
» Cloned the repo using TortoiseGit (which it seemed to do without any hassles)
» Opened the solution file using Visual Studio 2017 version 15.5.6 (hope this isn't the issue)
» Errors all around

Errors I'm getting:
» A lot of #include <*.h> lines are not finding the file (like Windows.h, Psapi.h, stddef.h, stdio.h, etc)
» Entire cmath file is giving errors (on the actual functions like ceil and cos and so on)

I know I might sound like an idiot, but I'm new and would very much like to play around with the source code (or at least get to build the .ASI first) and have nowhere else to go to ask for help.

Thanks for releasing the source though btw. It's bloody magical to even have access to this given how awesome this mod is.

**Comment by MAFINS** [comment]
Check the project settings and make sure the SDK version is set to the largest number

**Comment by ShawnPR1** [comment]
Will do once I get home. Thanks for the response btw

**Comment by ShawnPR1** [comment]
> Check the project settings and make sure the SDK version is set to the largest number

This worked quite well, but I'm still getting some errors when I build. Mainly that pugixml.hpp cannot be found as well as SimpleIni.h. Pastebin of the error console (if even needed): https://pastebin.com/iVugz6jT

I take it my visual studio is just outdated or maybe even my windows? I've set the SDK to "10.0.16299.0" seeing as that and "8.1" are the only numbers I see in the list of SDKs

**Comment by MAFINS** [comment]
Clone the repo recursively so that the submodules are also cloned.

**Comment by ShawnPR1** [comment]
Awesome thanks man the project builds now!

Thing is when I drop the .ASI in the game, the game just infinitely loads then crashes. Am I still doing something wrong or is this because it's not exactly updated to work with the latest version? I did see the changes made to the main.h and GTAmemory.cpp seem to add the latest version number of GTA at least.

I'm very new to all of this and don't expect an explanation of all the code don't you worry. I'll figure that out on my own in some way. I just wanna know the basics of why it might not be working for me at least. I'll close this ticket seeing as the issue is resolved, but would still like to know if I need to do something else on my end to get the actual mod to work properly.

Thanks for your time though. Much appreciated.
