### ISSUE TITLE
Menyoo Not Working in Fivem

### ISSUE THREAD

**Issue by GabbarFramework** [MAFINS/MenyooSP#322]
Menyoo is Not Loading in Fivem With Some Error In F8 Console I Have Put The menyoo.asi in plugins and other data folder in data/cache/subprocess but asi file not loading in fivem i saw it in f8 console

**Comment by SnowyLavina** [comment]
I'm getting the same issue

**Comment by GabbarFramework** [comment]
![image](https://user-images.githubusercontent.com/98814269/155460352-d410f689-abc7-488c-bec8-d083b3803836.png)

**Comment by cheeseburger847** [comment]
I think its ONLY a SinglePlayer Mod menu

**Comment by adversaru** [comment]
It works very good for FiveM right at this moment.

**Comment by ReadyP1ayerTwo** [comment]
> I think its ONLY a SinglePlayer Mod menu

Correction, it was made for sp but it does work in FiveM. iirc there are a few contributors here that help to keep it working with FiveM.

**Comment by adversaru** [comment]
> > I think its ONLY a SinglePlayer Mod menu
> 
> Correction, it was made for sp but it does work in FiveM. iirc there are a few contributors here that help to keep it working with FiveM.

This menu was made for the GTAV engine, FiveM runs on that.
The developer itself made all the accountable work, impressive one. 👍

**Comment by GabbarFramework** [comment]
still not working at all

**Comment by adversaru** [comment]
> still not working at all
It works correctly right at this moment for FiveM.

For you to be able to run it on FiveM, you should bypass the Scripthook.
How you do that ? Maybe that's the problem.

**Comment by GabbarFramework** [comment]
> > still not working at all
> > It works correctly right at this moment for FiveM.
> 
> For you to be able to run it on FiveM, you should bypass the Scripthook. How you do that ? Maybe that's the problem.

can u tell me that please

**Comment by The-UnXplained** [comment]
>The developer itself made all the accountable work, impressive one. +1

Correction, this menu mostly gets updated by contributors.. the original creator 'MAFINS' just sits back and continues to let silly kids like you believe he updates it..

**Comment by adversaru** [comment]
> > "The developer itself made all the accountable work, impressive one. +1"
> 
> lol - Correction, this menu mostly gets updated by contributors.. the original creator 'MAFINS' just sits back and continues to let silly kids like you believe he updates it..

You've proved how smart you are, that's it, no more needed 😂😂😂😂
Go and learn how Github works before running your mouth clueless, you keyboard warrior girl. 😚

**Comment by adversaru** [comment]
> > > "The developer itself made all the accountable work, impressive one. +1"
> > 
> > 
> > lol - Correction, this menu mostly gets updated by contributors.. the original creator 'MAFINS' just sits back and continues to let silly kids like you believe he updates it..
> 
> You've proved how smart you are, that's it, no more needed 😂😂😂😂 Go and learn how Github works before running your mouth clueless, you keyboard warrior girl. 😚
> 
> Edit: I see now why you said that 😂😂😂😂
 You uploaded 3 hours ago some useless shits to the project and now you're a contributor that made it all better i guess.
Congratulations! 👏👏😂😂😂😂😂

**Comment by adversaru** [comment]
> > > still not working at all
> > > It works correctly right at this moment for FiveM.
> > 
> > 
> > For you to be able to run it on FiveM, you should bypass the Scripthook. How you do that ? Maybe that's the problem.
> 
> can u tell me that please

That's why it doesn't work for you, because you need to bypass the ScriptHook.
You need to find a way to do it in order to make this work for FiveM. 👍

**Comment by TayMcKenzieNZ** [comment]
It does work for FiveM, you just have to install it correctly. Tons of YouTube tutorials

**Comment by GabbarFramework** [comment]
> It does work for FiveM, you just have to install it correctly. Tons of YouTube tutorials

Can You Recommend Anyone of It

**Comment by TayMcKenzieNZ** [comment]
Literally search YouTube. The reason Menyoo won't work for people on FiveM, is because every gamebuild needs to be supported within the ASI, therefore you need to update it, and if you don't know how, then you're wasting your time.

Tutorial: https://youtu.be/onN6yr3BXc8

Updating Menyoo ASI, Read and do it yourself, don't expect me to do shit for you:

https://forum.cfx.re/t/simple-trainer-wont-show-up/4183132
