### ISSUE TITLE
menyoo don't work

### ISSUE THREAD

**Issue by Splerger** [MAFINS/MenyooSP#325]
when i try to use it in fivem in the logs it says this:  Unable to load C:\Users\jamal\AppData\Local\FiveM\FiveM.app\plugins\Menyoo.asi - this ASI plugin does not claim to support game build 2545. If you have access to its source code, add `FX_ASI_BUILD 2545 dummy.txt` to the .rc file when building this plugin. If not, contact its maintainer.

**Comment by Cragj** [comment]
working on it its just the .rc file wants updating

**Comment by markos-giting** [comment]
Yes but how do I do that

https://m.twitch.tv/mildly_interesting2/home

**Comment by Cragj** [comment]
gotta reinstall fivem bud

**Comment by porcodiooid** [comment]
glad to see that people are replying to be helpful , latest time i read this section there were an fucking asshole trying to make us stop to ask for updates to match with the latest version of the game
