### ISSUE TITLE
basically this mod menu need constant updates to match with the latest version of the game otherwise there will always be some constant bugs that people will have to report , infact , some bug reports doesn't have nothing to do with the necessity to fix some bug , no , because the problem is just that the updates also have in the some attempt to prevent this mod menu from working , no problem developers , we don't give a motherfuckng damn about the online mode, so NO fucking excuses there, and someone fucking answer to all the issues reported

### ISSUE THREAD

**Issue by porcodiooid** [MAFINS/MenyooSP#329]

**Comment by porcodiooid** [comment]
basically this mod menu need constant updates to match with the latest version of the game otherwise there will always be some constant bugs that people will have to report , infact , some bug reports doesn't have nothing to do with the necessity to fix some bug , no , because the problem is just that the updates also have in the some attempt to prevent this mod menu from working , no problem developers , we don't give a motherfuckng damn about the online mode, so NO fucking excuses there, and someone fucking answer to all the issues reported

**Comment by MAFINS** [comment]
The community currently works on updating this project when possible. There is no obligation for anyone to update anything, but it is always welcome.

**Comment by porcodiooid** [comment]
> The community currently works on updating this project when possible. There is no obligation for anyone to update anything, but it is always welcome.

yes there is the obligation you retarded shit otherwise the problem wont' get solved , moron

**Comment by porcodiooid** [comment]
> The community currently works on updating this project when possible. There is no obligation for anyone to update anything, but it is always welcome.

and fucking cut it out with the bullshit of the non obligation , i know that technically none is obliged , but that doesn't fucking change nothing, and as decent people we don't have to feel forced to behave properly , and no , the fact that we aren't forced to do something right doesn't mean that we can avoid to do that , for fuck sake , you expressed the form of mind programming that you got exposed to , tons of morons before you blabbered this , cut it out , i am insulting ? you started by telling me this , remember that that insults aren't only just "fuck you" or "asshole" , there are also insults to the intelligence,  when people are expected to believe in something wrong

**Comment by porcodiooid** [comment]
so just fucking update this damn trainer
