### ISSUE TITLE
hey mafins

### ISSUE THREAD

**Issue by nobl3gg** [MAFINS/MenyooSP#33]
hey man I know you said you wouldn't update but I've built a career around map building currently supporting my family on custom maps and my twitch so my question is I got menyoo to work using version 1.0.0 but I get this weird issue where if I click on anything besides a spawned prop it gives me a scripthook v error and crashes and yes I've installed all new releases [any] suggestions ?

**Comment by MAFINS** [comment]
If you can (or get someone else to) download the 1.0.0 source using the tag and just replace the raycast.cpp file from the one in 1.0.1 and build (with optimisation disabled), that issue should be fixed.

I'm sure someone will update soon InShaAllah.

**Comment by yeye-alt** [comment]
Yyyyy... ray what?

**Comment by nobl3gg** [comment]
> If you can (or get someone else to) download the 1.0.0 source using the tag and just replace the raycast.cpp file from the one in 1.0.1 and build (with optimisation disabled), that issue should be fixed.
> 
> I'm sure someone will update soon InShaAllah.

i really hope so i want this again so bad and this is rockstars last update so its like mannnn

**Comment by rex2630** [comment]
Can someone please build IT with that filé?I need to edit map really bad

**Comment by sillyasskid** [comment]
> 
> 
> Can someone please build it with that file?I need to edit map really badly

http://www.mediafire.com/file/4wpzohze4xsd90q/1.0.1737.0-MenyooRelease.rar/file
