### ISSUE TITLE
Since the new Script Hook C update menyoo now crashes way more 

### ISSUE THREAD

**Issue by FiveO62** [MAFINS/MenyooSP#331]
Since the release of  the updated script hook V on may 4TH 2022 menyoo now crashes at the slightest of action’s, we all know not to go spamming the menu or scrolling super fast but it’s become ridiculous, even slowly navigating the menu it’s crashing sometimes jsut the menyoo but mostly the whole game. This has made map modding impossible I have been through multiple projects in the past days to crash midway through, I’m simply wondering if this is time for menyoo needing an update? , are other people experiencing this? Is it my game ? Or is this fault of script hook ?

**Comment by The-UnXplained** [comment]
https://www.mediafire.com/file/n6xpw2nmo6gcflh/Menyoo_08-05-2022.zip/file
