### ISSUE TITLE
{"message":"Artifacts download limit (1024 MB/day) exceeded."}

### ISSUE THREAD

**Issue by WithLithum** [MAFINS/MenyooSP#332]
AppVeyor may have implemented a quota limit based on a search.
You may want to either mirror your artifacts on GitHub or move your CI to GitHub Actions.

**Comment by OmegAlex10** [comment]
I doubt he'll ever do that

**Comment by WithLithum** [comment]
I am closing this since the project now uses GitHub Actions.
