### ISSUE TITLE
vehicle disappears after spawn

### ISSUE THREAD

**Issue by frnxx23** [MAFINS/MenyooSP#335]
every time I spawn a vehicle right after the motor starts it disappears. any ideas on what might be wrong?

**Comment by BROZZY228** [comment]
you have license gta v or pirate?
if you have license try to instal other vesion of menyoo 1.1.0 or 1.5.0 or try other versions of script hook v
[MenyooSPv1.5.0.zip](https://github.com/MAFINS/MenyooSP/files/8753463/MenyooSPv1.5.0.zip)
or try that version it is working on license

**Comment by Derison** [comment]
Since Menyoo hasn't received any updates lately, you'll have to use other addons to resolve this issue.
I installed [Add-On Vehicle Spawner](https://de.gta5-mods.com/scripts/add-on-vehicle-spawner) which lets you spawn all vehicles via Menyoo without getting them deleted when you try to drive them.

**Comment by The-UnXplained** [comment]
https://www.mediafire.com/file/1gp5n21wl3xorqz/Menyoo_30-05-2022.zip/file
