### ISSUE TITLE
hey people , all those bugs occur because the trainer isn't updated , not because it doesn't work , so now you know , ask for the updates in order for it to work with the latest version of the game , that will solve every problem 

### ISSUE THREAD

**Issue by porcodiooid** [MAFINS/MenyooSP#338]
as for those who make the trainer , just fucking update it , the fact that none is forcing you doesn't mean that you can let this thing to stay bugged

**Comment by DobbiCliky** [comment]
MAFINS closed down this project a long ago, go ahead and code it yourself if you don't like the instability, pull requests are open
