### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Duke-pixel** [MAFINS/MenyooSP#343]
How do I Install the Menu, cant find any .asi files oder MenyoMenu file

Im dumb pls help
Thank u

**Comment by LazytownSpo666** [comment]
if you installed menyoo wrong, delete menyoo folder, and listen.

if you don't have menyoo zip file yet (MenyooSP), download now. and if you already have one, that's fine.

now click on MenyooSP zip file, and then drag Menyoo ASI file and a folder (menyooStuff) into GTA V folder.
