### ISSUE TITLE
Out of RAM Crash on Vechile spawner menu

### ISSUE THREAD

**Issue by BedoAkgun** [MAFINS/MenyooSP#344]
So i was testing some car mods and then i realised i dont have ammo so i typed  "toolup" on cheat code screen. The thing i forgot was i was also selecting the vechile code, i pressed enter, the game froze and i got a out of ram error in my hands

thanks in advance

**Comment by DobbiCliky** [comment]
buy a computer (or more ram) because this probably just has to do with, well you not having enough ram

**Comment by BedoAkgun** [comment]
16 gigabytes isnt enough?
İdk what is then

25 Haz 2022 Cmt 00:26 tarihinde DobbiCliky ***@***.***> şunu
yazdı:
