### ISSUE TITLE
MAFINS, FUCKING UPDATE THIS DAMN MOD MENU

### ISSUE THREAD

**Issue by porcodiooid** [MAFINS/MenyooSP#352]
FOR FUCK SAKE "oh we let people to update the mod menu"  AS EVEN A SHIT HEAD LIKE YOU CAN NOTICE , IT ISN'T WORKING , NONE IS UPDATING , DAMN

**Comment by ReadyP1ayerTwo** [comment]
> FOR FUCK SAKE "oh we let people to update the mod menu" AS EVEN A SHIT HEAD LIKE YOU CAN NOTICE , IT ISN'T WORKING , NONE IS UPDATING , DAMN

are you dumb, stupid or dumb. fucks like you need to stop flooding my inbox

**Comment by porcodiooid** [comment]
@ReadyP1ayerTwo just go fucking kill yourself you pointless thing , you don't count
