### ISSUE TITLE
Menyoo.asi - this ASI plugin does not claim to support game build 2545.

### ISSUE THREAD

**Issue by GameHackerTV** [MAFINS/MenyooSP#354]
Menyoo.asi - this ASI plugin does not claim to support game build 2545. If you have access to its source code, add `FX_ASI_BUILD 2545 dummy.txt` to the .rc file when building this plugin. If not, contact its maintainer.

please help, I need this plugin urgently

**Comment by Cragj** [comment]
Gotta reinstall sorry bud

**Comment by Cragj** [comment]
> Gotta reinstall sorry bud

by that i mean like reinstall FiveM again
