### ISSUE TITLE
Menyoo.asi in Fivem

### ISSUE THREAD

**Issue by FdeFeliope** [MAFINS/MenyooSP#361]
Menyoo.asi - this ASI plugin does not claim to support game build 2545. If you have access to its source code, add FX_ASI_BUILD 2545 dummy.txt to the .rc file when building this plugin. If not, contact its maintainer.

please help, I need this plugin urgently

**Comment by TayMcKenzieNZ** [comment]
https://forum.cfx.re/t/simple-trainer-wont-show-up/4183132/3
