### ISSUE TITLE
Can not find any .asi files 

### ISSUE THREAD

**Issue by pinkieeeee** [MAFINS/MenyooSP#366]
Uhm so idk if I'm just dumb or somthing but i can't seem to find the output.asi or any .asi file in general. Can someone just describe to me how to install/what to copy exactly?

Hope someone can help :)

**Comment by DylanDevelops** [comment]
Are you just asking how to install the menu? If so, when you download the folder [here](https://github.com/MAFINS/MenyooSP/releases/tag/v1.5.0). The file you download is called MenyooSP.zip. Drag the "menyooStuff" folder and the "Menyoo.asi" file into your main GTA directory and that should install it for you.

**Comment by pinkieeeee** [comment]
oh yeah thanks i think i downloaded the source code on accident. Maybe you could change the installation guide and tell the people to make sure that they have downloaded the right thing?

**Comment by DylanDevelops** [comment]
Already did! Thank you for the suggestion. It just needs to be approved on the official document :)

**Comment by DylanDevelops** [comment]
Awesome I updated the installation instructions and they are on the main branch now. Thanks for suggestion. You can close this issue now since it's fixed.
