### ISSUE TITLE
Cant download from ci.appveyor.com/project/MAFINS/menyoosp/build/artifacts

### ISSUE THREAD

**Issue by Gta5KoRn** [MAFINS/MenyooSP#368]
Again. 
This was posted before, but was ignored by the authors.
Cant download from https://ci.appveyor.com/project/MAFINS/menyoosp/build/artifacts
{"message":"Artifacts download limit (1024 MB/day) exceeded."}

**Comment by DylanDevelops** [comment]
Does it let you install from [https://github.com/MAFINS/MenyooSP/releases](https://github.com/MAFINS/MenyooSP/releases)?

**Comment by ErickPhoenix** [comment]
> Does it let you install from https://github.com/MAFINS/MenyooSP/releases?

Yes, I can download from this but the one on the site Gta5KoRn shared is updated

**Comment by DylanDevelops** [comment]
Just stick to the GitHub repository because the other ones just might not be up to date. You can always find the most up to date one here.

**Comment by ErickPhoenix** [comment]
But for me the GitHub version don't have the new cars. I don't know why

**Comment by DylanDevelops** [comment]
I believe we are still working on updating the mod for the new vehicles. Just keep an eye on this repository for when an update is pushed out for the menu.

**Comment by Gta5KoRn** [comment]
MAFINS updated to 1.0.212 under that link. But its not possible to download 🤦‍♂️
