### ISSUE TITLE
How do I install the new Menyoo update?

### ISSUE THREAD

**Issue by ErickPhoenix** [MAFINS/MenyooSP#371]
How do I install the new update to get the cars from the new DLC? 
I'm new here so I know nothing about this

**Comment by a12saucy** [comment]
same im confused too.

**Comment by The-UnXplained** [comment]
**There is no Menyoo update, not by the original creator anyway..** 

If you really want an updated version you have three options:

_1, Find my version when i update and release it..
2, Hope a contributor updates it..
3, Update it yourself.._

**Comment by Voye-voda** [comment]
@The-UnXplained Why don't you have your version here on github?

**Comment by The-UnXplained** [comment]
Let's just say myself and MAFINS don't get along.  - I' m almost finished updating my version, just got the new weapons to add later.. I'm sure if you look hard enough you will find a link to it when i release it. ;)

**Comment by DylanDevelops** [comment]
@The-UnXplained Woudl you be willing to show me how one would update a mod like this? I'm new to single player modding so I'm just curious.

**Comment by Cxsonn** [comment]
@The-UnXplained, when will your version of the mod be released? I live in the US, so at around what time for you?

**Comment by Cxsonn** [comment]
@The-UnXplained, I'd just like to notify you that the newest weapons added to GTA Online don't work in with your version of the Menyoo Trainer. I'm not sure if you're aware of this or not, but I thought I'd late you know regardless.

**Comment by The-UnXplained** [comment]
Had lots of issues adding the new weapons but thought i had resolved them because they work fine for me now..

**Comment by Cxsonn** [comment]
@The-UnXplained, it could just be an issue with my game, but IDK. I'm going to try and reinstall it and see if it still doesn't work. I'll update you.

**Comment by The-UnXplained** [comment]
@DylanDevelops - Theres a few things that has to be updated, for a start the game version number found in: Solution/source/main.h has now changed to 1_0_2699_0.  Then theres the Global's in GTAmemory.cpp that have to be updated.. for example, Player Swim Speed is 0x8, 0x10C8, 0x170. - You can find the rest out for yourself.. :)

**Comment by The-UnXplained** [comment]
@Cxsonn It's most likely the way i coded them new weapons, when i try 'WEAPON_PRECISIONRIFLE' visual studio throws tons of errors,  i had this same issue befor with a previous update. It would be interesting to know if the Heavy Rifle works ok for you..

**Comment by DylanDevelops** [comment]
> @DylanDevelops - Theres a few things that has to be updated, for a start the game version number found in: Solution/source/main.h has now changed to 1_0_2699_0. Then theres the Global's in GTAmemory.cpp that have to be updated.. for example, Player Swim Speed is 0x8, 0x10C8, 0x170. - You can find the rest out for yourself.. :)

Is there a website that shows all the things that you need to update?

**Comment by Cxsonn** [comment]
@The-UnXplained, the heavy rifle works fine, it's just the service carbine and the precision rifle that don't work.

**Comment by The-UnXplained** [comment]
@Cxsonn can you spawn the new cars in ok..

**Comment by The-UnXplained** [comment]
@DylanDevelops The best thing for you to do is join some gta, modding and codding site's & forums and maybe look at some smaller projects first so you can get a better understanding of things..

**Comment by DylanDevelops** [comment]
> @DylanDevelops The best thing for you to do is join some gta, modding and codding site's & forums and maybe look at some smaller projects first so you can get a better understanding of things..

Thank you for the advice! I'm pretty good at C# but really haven't gotten into game modding until now!

**Comment by mistahwolf** [comment]
The-UnXplained, glad to hear you're working on an update! If you could look into a problem that occurs since the (spits) 'contract dlc', Menyoo used to load in maps with up to 2000 props no prob. Now if you have more than 900, the error 'An Exception occurred while executing Menyoo.asi (0x000007FEC87A73C0), id 40.' Others have said it was a 'dlc incompatiblity and just update the ASI', but everything worked fine until the (spits) contract update. Even with your last update the game still crashed when trying to load in large maps.

**Comment by OmegAlex10** [comment]
> The-UnXplained, glad to hear you're working on an update! If you could look into a problem that occurs since the (spits) 'contract dlc', Menyoo used to load in maps with up to 2000 props no prob. Now if you have more than 900, the error 'An Exception occurred while executing Menyoo.asi (0x000007FEC87A73C0), id 40.' Others have said it was a 'dlc incompatiblity and just update the ASI', but everything worked fine until the (spits) contract update. Even with your last update the game still crashed when trying to load in large maps.

I am also having the same issue (using The-UnExplained's menyoo as a last resort solution), instead I get the same error but with id.35/36 when I load over 700 props or when simply editing npc's spawned with spooner

**Comment by OmegAlex10** [comment]
One "fix" was removing most DLC addon vehicles, but it only prevented the game from insta-crashing with id.35 the second I load the map

**Comment by G-Howsam** [comment]
@The-UnXplained The Weaponized Ignus crashes the whole game. I don't know if there are any more vehicles that crash the game, but that one if a for sure crash

**Comment by The-UnXplained** [comment]
Apparently rockstar has added some new vehicles, clothes and possibly some other stuff in the game files that are currently just placeholders for the 'expanded & enhanced edition' - so expect issues for the time being.

**Comment by Damaux** [comment]
> Let's just say myself and MAFINS don't get along. - I' m almost finished updating my version, just got the new weapons to add later.. I'm sure if you look hard enough you will find a link to it when i release it. ;)

Ok I found your version on your website. But why not have it on Github or other open project site? First look aty your website and it says not secured and it looks sketchy lol
