### ISSUE TITLE
Menyoo crashing game entering a cutscene in online

### ISSUE THREAD

**Issue by Tessio** [MAFINS/MenyooSP#373]
I use menyoo since the last update with a paid menu mod that manages to load the ".asi" files without being detected.

The problem is that in this update something was broken, menyoo can be used online but when entering an interior or mission cinematic it will bug and sometimes even close the game.

I would like to know if there is an optimized version for it or a solution, since no paid menu compares to the functions of the menyoo

I currently use the version of @The-UnXplained

thanks in advance c:

**Comment by The-UnXplained** [comment]
In my version, i removed some remnants of the coding relating to online and i don't intend to add them back. Lets not forget this is a single player menu.. i recommend you look for other modified versions.

**Comment by MAFINS** [comment]
Menyoo is only for single-player story mode.
