### ISSUE TITLE
Error when compiling menyoo

### ISSUE THREAD

**Issue by THCPotHead** [MAFINS/MenyooSP#377]
![image](https://user-images.githubusercontent.com/110537430/182657957-86d5d5db-64f4-46a9-ac35-18cde4fd56cf.png)

I get these errors when trying to compile menyoo. Anyone know how to fix? please help! nothing is edited yet. I just try to compile first before changing stuff so i know it works

**Comment by THCPotHead** [comment]
I just want to add that I do have all the external stuff downloaded and put in the right directory

**Comment by MAFINS** [comment]
Make sure you used --recurse-submodules when cloning the repo or downloaded the correct versions (check commit ids) of simpleini (NOT the latest build).
And that you're using the appropriate C++17 compiler too if that doesn't fix it.
Feel free to reopen the issue if needed.
