### ISSUE TITLE
Menyoo is unable to build and unable to be downloaded

### ISSUE THREAD

**Issue by Hakkodevelopment** [MAFINS/MenyooSP#379]
According to: https://www.gta5-mods.com/scripts/menyoo-pc-sp. The new download link to get updates is https://ci.appveyor.com/project/MAFINS/menyoosp/build/artifacts. Though whenever you attempt to download from there it gives you the error {"message":"Artifacts download limit (1024 MB/day) exceeded."} Because I was unable to download it, I decided to build it from source, which I did back in March for the contract DLC, though you have changed something to make it impossible to build in the latest update. 
![image](https://user-images.githubusercontent.com/67168651/183258488-62684969-c6e9-4a83-a4c2-2f4953901039.png)

I don't understand why you decided to take up space on a different platform that doesn't even work right rather then updating it here, on your GitHub repo or on the GTA V Mods page...

**Comment by MAFINS** [comment]
Make sure you used --recurse-submodules when cloning the repo.
And that you're using the appropriate C++17 compiler too if that doesn't fix it.
Feel free to reopen the issue if needed.

**Comment by AT-Crazy-Gamerz** [comment]
Can you Please update the Menyoo Trainer I am facing a issue when I try to spawn a tank my game crash and i am using all the latest version to all script hook v script hook dot net this is happing to me please upgrade menyoo trainer
