### ISSUE TITLE
Menyoo Customs speed limit (low Top Speed value) doesn't work for boats

### ISSUE THREAD

**Issue by metoxys** [MAFINS/MenyooSP#380]
Even setting it to 1, that value seems to have no effect on boats

**Comment by metoxys** [comment]
Still a thing in the latest version

Consider looking into it @itsjustcurtis

**Comment by itsjustcurtis** [comment]
Able to replicate the issue, looking into potential causes

**Comment by metoxys** [comment]
Confirmed fixed in v1.7.3
