### ISSUE TITLE
menyoo crashing when spawning cars

### ISSUE THREAD

**Issue by jagsirkhokhar19177** [MAFINS/MenyooSP#383]
menyoo crashing when spawning some cars

i found this cars list 

suv = Astron custom
muscle = Arbiter gt
sports = S95
super = Weaponized ignus
super = Cyclone II 

please fix this

**Comment by jagsirkhokhar19177** [comment]
thanks 

but how i can remove this cars names from menyoo vehicles list

**Comment by Vaxee** [comment]
Also you can find the car you are interesred in the Spooner mod

**Comment by OmegAlex10** [comment]
The only way to avoid the crash is to prevent the "vehicle highlight" that menyoo does to show you what you are actually spawning, since it involves the actual car model.

**Comment by Alilbnz** [comment]
Me too

**Comment by First-Last1998** [comment]
Menyoo crashes on my computer when I copy entities such as NPCs, and cars. It also sometimes crashes when I move items around using F9. The only mods I have installed are Menyoo, ScriptHookV, and Vehicle Controller mod.
