### ISSUE TITLE
[FIVEM] - Game crash when ANY vehicle is spawned!

### ISSUE THREAD

**Issue by ArsiTheFox** [MAFINS/MenyooSP#393]
I am running FiveM with Menyoo installed and anytime I try to spawn a vehicle I get this crash error:
![FiveM_DumpServer_m3MFIsGeiQ](https://user-images.githubusercontent.com/24835664/187350842-b79b31dc-780e-42bc-bed1-2fed09fab018.png)
![FiveM_GTAProcess_FgEaBXSuk6](https://user-images.githubusercontent.com/24835664/187350844-132f625e-506d-460c-bfc9-089f015dc3df.jpg)
Mods I have loaded:
![explorer_EKE2R1dRVg](https://user-images.githubusercontent.com/24835664/187350928-55191d95-bd4d-4d83-aafb-90a1abc3599a.png)

**Comment by OmegAlex10** [comment]
You sure that your dinputt8.dll is up to date? Isn't it from 2015?

**Comment by OmegAlex10** [comment]
Also depends what cars, avoid spawning the PS5 ones

**Comment by ArsiTheFox** [comment]
> You sure that your dinputt8.dll is up to date? Isn't it from 2015?

The DInput was a file given by Updated ScriptHookV
Also the car in the picture the 811 was the car I tried spawning. I also tried spawning a normal BMX bike and it also crashed

**Comment by OmegAlex10** [comment]
Just to troubleshoot if it's either menyoo or scripthook or anything fivem related that causes the issue

**Comment by Vaxee** [comment]
Do you have a folder menyoostuff? All models are stored in this folder(Besides PS5/XBX's cars)

**Comment by Vaxee** [comment]
[MenyooSP.zip](https://github.com/MAFINS/MenyooSP/files/9456024/MenyooSP.zip)
This is not the latest version of Menyoo but here is this folder

**Comment by ArsiTheFox** [comment]
> [MenyooSP.zip](https://github.com/MAFINS/MenyooSP/files/9456024/MenyooSP.zip) This is not the latest version of Menyoo but here is this folder if need be

I do already have the subprocess folders but I am about to try to mod the game without fivem

**Comment by ArsiTheFox** [comment]
It may not like FiveM
