### ISSUE TITLE
dlc pack expanded and enhanced-cyclone 2

### ISSUE THREAD

**Issue by lcalixto2012** [MAFINS/MenyooSP#394]
there is an unspawnable vehicle code 'CYCLONE2' that causes the game to crash as soon as you try to spawn it.  Its better to fix it or remove it in future updates.

**Comment by OmegAlex10** [comment]
Dlc vehicle incompatible with pc versions of gta 5, just avoid them.

**Comment by OmegAlex10** [comment]
Any content fron ps5 or xbox series x will crash the game

**Comment by synnkfps** [comment]
> Dlc vehicle incompatible with pc versions of gta 5, just avoid them.

"Just avoid them."
ah yes i will decorate every single unspawnable vehicle so i can avoid them!1!!1

**Comment by OmegAlex10** [comment]
What?

**Comment by patronhullie** [comment]
has it been fixed yet?
