### ISSUE TITLE
menyo v1.5.0 crash

### ISSUE THREAD

**Issue by thekiller199365** [MAFINS/MenyooSP#397]
When ever i load a map i get this message and then it crashes on the latest version. "An exception occurred while executing 'Menyoo.asi' (0x00007FFB81D1B300), id 46"

**Comment by The-UnXplained** [comment]
The menu on here is very outdated so might be the reason it's crashing. To get an updated version, you can either use mine (link on my profile), wait forever for the original creator, a contributor or learn to update it yourself.

**Comment by thekiller199365** [comment]
i tried yours and got the same result. i go to load a map that has vehicles and it crashes.

**Comment by OmegAlex10** [comment]
@thekiller199365 go to the "When is the next menyoo update" issue post (asked by Master-Osa).I linked a fix to those menyoo.asi crashes. Had a map that kept crashing the game instantly with id36/37/35 and 41, entirely random. Now it's fixed for me, hooefully it works for you too

**Comment by thekiller199365** [comment]
i tried that one also. that was one of the first places i went  before i posted.

**Comment by OmegAlex10** [comment]
> i tried that one also. that was one of the first places i went before i posted.

Could be a modded vehicle.. try removing all of them and see if it changes anything.. More than that, I wouldn't know besides recommending taking another look at that link

**Comment by OmegAlex10** [comment]
> @thekiller199365 go to the "When is the update" issue post (issue #384 asked by Master-Osa).I linked a fix to those menyoo.asi crashes. Had a map that kept crashing the game instantly with id36/37/35 and 41, entirely random. Now it's fixed for me, hopefully* it works for you too

Somewhere in the middle of the post is a tutorial and step by step guide to apply an .asi fix with a tool, in case you missed it

**Comment by thekiller199365** [comment]
its a map with i think 80 cars anything below 7 cars is fine. i tried it with just one base game vehicle and spawned the map with 6 of the same vehicle and it spawned without crash and then i tried it with 80 of the same vehicle to check if it would spawn and it crashed with that error code. i just tried the resource hacker thing and the .res and same result. Not sure what else to do.

**Comment by OmegAlex10** [comment]
Is it a modded vehicle? If so try replacing it with something else (or ditch it entirely). If the game crashes instantly, remove that vehicle from dlc list (if it's modded), that will wipe that vehicle from the map's spooner list. I really hope it works out!

**Comment by OmegAlex10** [comment]
Try for example 80 other modded vehicles (same/not the same type). Last resort solution would be a custom xml file for addon vehicles (I doubt you don't have the right one, otherwise the game would crash on startup)

**Comment by thekiller199365** [comment]
so ive tried different cars and same cars and still same issue. its not modded cars, ive tried base game and dlc cars and still not working.

**Comment by OmegAlex10** [comment]
Then probably your map is corrupted

**Comment by thekiller199365** [comment]
I dont know what it could be. It worked before. All im doing is spawning them, save them to a file and to test it i delete entries and then load the file and game crashes.

Even when i start the game and load the file it crashes.

**Comment by OmegAlex10** [comment]
The only causes of this issue (the sign being menyoo.asi core crashing with id 36 to 42) that I know are: -incompatible menyoo with game version
-incompatible update.rpf with game version
-broken menyoo.asi code
-broken modded addon vehicles (programmed by imbeciles)
-Corrupted menyoo spooner file
-Probably some modded vehicles beingc incompatible.
-Incorrect adddon vehicle .xml file (forgot it's name but you can find it as custom.xml for addon vehicles)
If you really, really want to fix this issue, it's worth rechecking all of these causes from 0 (reinstalling all mods, new and compatible menyoo from that link to that forum with asi fixes, updating update.rpf from OpenIV, or reinstall Gta 5. A crap tone to do, ik, but this is all I have left, I'm sorry...
