### ISSUE TITLE
Vinewood teleports

### ISSUE THREAD

**Issue by Yhwhdios** [MAFINS/MenyooSP#40]
MAFINS or anyone who knows C++, I wrote a teleport to the Main Casino Floor (haven't done the others yet), could you check it out for me. Also very I'm new to scripting, so there may be many mistakes (PS I used the Arena War teleports as a reference)
https://drive.google.com/open?id=1pI1yZDtvpOzwRjKtKIdaHOJAzZtf_Z1R

**Comment by MAFINS** [comment]
Link seems to be down. You may re-open if this is of interest.
