### ISSUE TITLE
menyoo cannot save anything 

### ISSUE THREAD

**Issue by SAJMONKO1220** [MAFINS/MenyooSP#401]
gta v is set to read only and cannot be change it change to read only asap when i change it to edit mode

welp i tried everywhere but this is best option i have. so thanks :D

**Comment by OmegAlex10** [comment]
That's because hard drives in general ARE ROM/Read Only Memory.... What even is the actual problem????

**Comment by OmegAlex10** [comment]
Can you be more specific, ...or even relevant to menyoo
