### ISSUE TITLE
MOM MENU DOSENT POP Up

### ISSUE THREAD

**Issue by remus019** [MAFINS/MenyooSP#402]
idid everything coreectly installed it nd when ipress f8 nothig happends

**Comment by OmegAlex10** [comment]
Do you even have scripthook and scripthookdotnet installed???

**Comment by psvks** [comment]
install asiloader and scripthook?

**Comment by blairbear22** [comment]
im having the same problem and have everything up to date i dont know what to do either

**Comment by lonewolf0708** [comment]
Do you have the latest [Script Hook V](http://www.dev-c.com/gtav/scripthookv/) installed? Are the Menyoo.asi and MenyooStuff folder in the same location as GTAV.exe?
