### ISSUE TITLE
Menyoo not loading/menu not popping up.

### ISSUE THREAD

**Issue by KingGhost18** [MAFINS/MenyooSP#405]
When I press F8 (which is the default hotkey, and my current hotkey) It doesn't pop up. I have the latest scripthookv, and scripthookvdotnet, installed. Could somebody tell me why, and how to fix it? I have re-installed menyoo multiple times, I have the asi manager installed (OpenIV) And everything. Thanks.

**Comment by TheGodSlayerAndroxus** [comment]
me too ,im crying bro
