### ISSUE TITLE
Hi guys! Thank you for continuing to work on the Menyoo! 

### ISSUE THREAD

**Issue by Pehotinec78** [MAFINS/MenyooSP#409]
In the new update, the main problem, and a very important one that I noticed, is problems with tuning the car. Tuning is either reset or not installed at all. Among other things, I would like to see the new weapons that Rockstar added in update 2699. Hope you fix the bugs! Thank you!

**Comment by itsjustcurtis** [comment]
can you be more descriptive on the problem with tuning? If there is no tuning at all, are you sure this isn't a modkit issue rather than a problem with menyoo?

**Comment by Pehotinec78** [comment]
> can you be more descriptive on the problem with tuning? If there is no tuning at all, are you sure this isn't a modkit issue rather than a problem with menyoo?

Why do I think this is a problem with the 1.7.1 update, because in version 1.5.0, custom for vehicles works fine and nothing is reset.

**Comment by itsjustcurtis** [comment]
> 
This sounds like a bug with the preview options. I have noted some mistakes in my latest code and am currently working on a fix. The intent is that when you select an option, it will apply your part, then exit to the previous menu. 

For the time being, you can scroll to the bottom of the Menyoo Customs screen, and turn off "LSC Style Tuning" to go back to what you will be used to in 1.5.0 until I release a fix.

**Comment by Pehotinec78** [comment]
> > 
> 
> This sounds like a bug with the preview options. I have noted some mistakes in my latest code and am currently working on a fix. The intent is that when you select an option, it will apply your part, then exit to the previous menu.
> 
> For the time being, you can scroll to the bottom of the Menyoo Customs screen, and turn off "LSC Style Tuning" to go back to what you will be used to in 1.5.0 until I release a fix.

OK, thanks

**Comment by itsjustcurtis** [comment]
> 

The updates from me are sent as a pull request to this repository for MAFINS to accept. If they deem the code appropriate, it will be merged with this and a new release created. Until that Pull request is approved the updates wont be available for download.

With regards to your teleport problem, please raise as a separate issue.
