### ISSUE TITLE
Ped don' t want to be in water

### ISSUE THREAD

**Issue by pat225** [MAFINS/MenyooSP#415]
Hello, I want to create my film by using Menyoo, REditor. I want to create water scene, where Ped is drowning, but problem is, that I can' t record this scene, because Ped is runing out of water when I place him to water by obj. Spooner. How can I to force Ped stay n water? Thanks for help.

**Comment by OmegAlex10** [comment]
Ik the animation bit sounds pointless, but you don't have them to work in this case. Just as a reset button for peds

**Comment by OmegAlex10** [comment]
Try freezing the ped, or turning off "dynamic" setting.  When I'll arrive home I'll experiment with all the issues you had and see if I can recreate them or work around them

**Comment by pat225** [comment]
I disable Dynamic and after put PED to water, and go out again. Thank you for help, I wait for next tips.

**Comment by OmegAlex10** [comment]
Before I'll start, can you tell me exactly what trainer mods and menyoo version you have? It could also be a conflict between mods. Tomorrow I'll be working on it

**Comment by OmegAlex10** [comment]
Also... I'm extremely unfamiliar with the UI bar at the bottom. Menyoo never had key binds. Is this actually spooner mode within an official menyoo trainer?

**Comment by pat225** [comment]
Answer for first question: I have newest Menyoo version, which is released 6 days ago, v1.7.1. I have any other mods.

Answer for second question: Yes, this is only Menyoo. I don´t use any other mods.

**Comment by mistahwolf** [comment]
Do this; 1. Spawn your ped. 2. Freeze Ped in place. 3. Turn off Dynamic. 4. Manually place ped in water (ped will not drown long as it is frozen. 5. Dig through the animation list, there are drowning animations (I'm not going to try and name them all.) 6. Make sure the animation is on 'loop' or the ped will just stop and you'll have to apply the animation again. 7. Record your video....

**Comment by OmegAlex10** [comment]
Since a mod conflict doesn't seem to be the case since, according to what you told me, menyoo is the only mod you have currently installed. I'd still recommend a fresh reinstall of your mods
