### ISSUE TITLE
Teleports in Menyoo Malfunctioning....

### ISSUE THREAD

**Issue by mistahwolf** [MAFINS/MenyooSP#416]
Menyoo isn't letting the player access the teleport markers on foot. If in a vehicle and it's set for that, then no prob. This started happening after the 2699 update. Since Menyoo crashing when changing outfits on an MP ped more than once, the solution was to 'soul steal' a ped to remedy the problem. Up until the 2699 update, the teleportals worked fine when on foot. Even starting with a skin over a main player ped doesn't work either. I first thought it was a conflict with the Mod 'Teleportals'. But the problem persists after removing it. Again, using a teleport marker while in a vehicle works fine. Others have mentioned having this issue to me. If you could take a look at this that would be great. Thanks.

**Comment by MAFINS** [comment]
Discussion moved to #423
