### ISSUE TITLE
Going Back when selecting inside Menyoo Customs

### ISSUE THREAD

**Issue by superjaja05** [MAFINS/MenyooSP#424]
Hey, sorry i'm not sure if its a bug or an intended feature.

Recently i noticed that when i select something in Menyoo Customs (for example change engine or paint color) , once selecting the option i want, it goes back to the previous menu (like if backspace was pressed).

It is quite annoying since it also puts the selection back to the top , so i have to go down again every single time

Is it a bug? or a setting i accidently changed?

Video of the issue: https://www.youtube.com/watch?v=DLGOz0gA5IE 
(Yes the quality sucks, but my connection is too bad to have higher resolution xd)

**Comment by itsjustcurtis** [comment]
This is an intended function designed to more closely emulate LS Customs menu navigation. You can turn it off via the "LSC Style Menu" option at the bottom of Menyoo Customs
