### ISSUE TITLE
Bug starting mission with Lester

### ISSUE THREAD

**Issue by 360matt** [MAFINS/MenyooSP#43]
I have a problem, I would go on a mission with Lester but then Michael has a bug, I'm frozen in this picture.
With the Object Spooner I was able to get into the building (Lester's Den) and saw Michael moving forward and back a few milliseconds later.

![unknown](https://user-images.githubusercontent.com/28982110/63364352-b1051100-c375-11e9-9b93-d74f3c53cd98.png)

![image](https://user-images.githubusercontent.com/28982110/63364410-c9752b80-c375-11e9-947b-3e234400c0d4.png)
the map flashes

![image](https://user-images.githubusercontent.com/28982110/63364469-ead61780-c375-11e9-87dd-2e9fda6ad7aa.png)
Michael moves away from the yellow circle and comes back immediately

thank you in advance for solving this problem

**Comment by MAFINS** [comment]
Is this only with Menyoo installed?
