### ISSUE TITLE
Unable to save file 

### ISSUE THREAD

**Issue by Silverman024** [MAFINS/MenyooSP#432]
hi if i try to save my map i have information unable to save file please help me

**Comment by yomamadas** [comment]
remove write protection form folder or move whole gta dir out of program files

**Comment by Silverman024** [comment]
> 

can you give me precise guide because i dont understand how i can do this

**Comment by lonewolf0708** [comment]
Right-click the game folder, go to properties (1st image) and clear the Read-Only flag (2nd image) then hit apply, then save.
![image](https://user-images.githubusercontent.com/51030924/210027069-93edf247-3948-40ed-b123-9c5a104dd089.png)
![image](https://user-images.githubusercontent.com/51030924/210027191-c2d30a8b-ee31-4d1d-b438-c1e9546196c0.png)
