### ISSUE TITLE
Default speed limiter value of spawned cars is too low

### ISSUE THREAD

**Issue by metoxys** [MAFINS/MenyooSP#44]
In the Menyoo Customs screen there is the speed limiter. In my opinion, the default value when you spawn the cars is set too low, it is easy enough to be limited by it.

I suggest making the default value a really high number (say, 100000) so that this feature does not mess with you unless you intentionally want to use it.

**Comment by MAFINS** [comment]
The default value is not pre-enabled. Only when the value is changed is when it starts running.
