### ISSUE TITLE
Problem with DLC cars.

### ISSUE THREAD

**Issue by Pavle112** [MAFINS/MenyooSP#444]
When I create a vehicle after a few moments it kicks me out of the vehicle or deletes it. How do I fix this problem? I had this problem before but somehow it just got better.

**Comment by metoxys** [comment]
Duplicate of #427

**Comment by Pavle112** [comment]
Ok and how to fix?

**Comment by Pavle112** [comment]
Ok thanks!

**Comment by metoxys** [comment]
Confirmed fixed in v1.7.3

Can close this @MAFINS
