### ISSUE TITLE
[Suggestion] Menyoo Customs: Online-legal color category for interior and dashboard colors

### ISSUE THREAD

**Issue by metoxys** [MAFINS/MenyooSP#445]
As of now, the color list in the rim color selection is restricted to colors which are legal in PC Online (as in, they don't get reset to 0 (Black)).

The interior and dashboard/accent color customization doesn't restrict anything and behaves similar to primary/secondary color selection.

I suggest adding a similar restricted menu for those as they also have a whitelist on PC Online. A few years ago I made [an overview](https://docs.google.com/spreadsheets/d/e/2PACX-1vQA_X8tRfhYwvuHF10HCIpIFxXanmjP67NIpSqbmR7Kp2pi847OOjDZVs6o2N2s6s5FZah6sxnSYJYM/pubhtml?gid=1434824247&single=true) listing which colors are legal in which slot. In theory you can also count 0 (Black) as a legal dashboard color as it is a fallback for an illegal color.

**Comment by itsjustcurtis** [comment]
Is this a suggestion to limit the dashboard colours to the same list that Wheels and Pearlescents reference? Or extending the list out to for the latter two to what the dashboard options are?

**Comment by metoxys** [comment]
> Is this a suggestion to limit the dashboard colours to the same list that Wheels and Pearlescents reference? Or extending the list out to for the latter two to what the dashboard options are?

| Category | Current status | Proposal | Notes |
|---|---|---|---|
|Primary|Full selection with submenus|Leave as it is|
|Secondary|Full selection with submenus|Leave as it is|
|Pearlescent|LSC Wheel color list|**LSC Pearlescent color list**|The list used by Menyoo is wrong. Consider my spreadsheet for the list of legal color IDs
|Wheels|LSC Wheel color list|Leave as it is|
|Interior Colour|Full selection with submenus|**LSC Interior color list**|Consider my spreadsheet for the list of legal color IDs
|Dashboard Colour|Full selection with submenus|**LSC Dashboard color list**|Consider my spreadsheet for the list of legal color IDs, also consider including 0 (Black)

**Comment by itsjustcurtis** [comment]
Looking into this now. Currently the wheels list is hard-coded. Pearls are read from the games carcols file but are not yet utilised, so that should be a simple fix. All 4 currently read from the pre-made wheels list. I can quite easily make the pearls read from the correct area, however interior and dashboard will require a new array of colours creating. That said, I may be able to fix it so I have a complete list for _all_ options, which then omits specific ones not included for a given option.

**Comment by metoxys** [comment]
> Looking into this now. Currently the wheels list is hard-coded. Pearls are read from the games carcols file but are not yet utilised, so that should be a simple fix. All 4 currently read from the pre-made wheels list. I can quite easily make the pearls read from the correct area, however interior and dashboard will require a new array of colours creating. That said, I may be able to fix it so I have a complete list for _all_ options, which then omits specific ones not included for a given option.

If it helps you, I'll take a few minutes to write the arrays for you; you only need to let me know
