### ISSUE TITLE
Menyoo Customs: Bike wheels are not being saved properly

### ISSUE THREAD

**Issue by metoxys** [MAFINS/MenyooSP#447]
Reproduce: Customize bike, select different rims for front and rear wheel, save bike to file, spawn saved bike from file

Rim selected for the front wheel is on the rear wheel as well

**Comment by metoxys** [comment]
Just for additional info, I am sure that this is a bug about __saving__ bike wheels and not __spawning__ them, because bikes I saved in earlier versions of Menyoo spawned fine with different rims

**Comment by itsjustcurtis** [comment]
Entirely possible, recent changes to the save vehicle script may have messed with that slightly

**Comment by metoxys** [comment]
> Entirely possible, recent changes to the save vehicle script may have messed with that slightly

If it helps, according to my notes, in previous Menyoo versions, ID 23 is front rim, ID 24 is rear rim

**Comment by metoxys** [comment]
![image](https://user-images.githubusercontent.com/6764458/209321975-9d7b8009-7c7b-44c8-9dba-090759624d3a.png)
@itsjustcurtis 
Now, when customizing bike rear wheels, I can change the rim by pressing Enter, but the icon confirming which rim is on there is not changing  
Also the saving is not working just as before

**Comment by itsjustcurtis** [comment]
I've come across this before, I think its an issue with how the menu is rendered. The saving of wheels is separate, I'll have a look at whats going on

**Comment by itsjustcurtis** [comment]
![image](https://user-images.githubusercontent.com/70447190/209410369-23f65e9d-5928-4148-97a4-f0d7097da846.png)

Looking at the wheel indexes, the list actually skips a number of indexes, making it almost impossible to get the marker to show properly. This is going to take a lot of effort to make work properly by the looks of things.

**Comment by metoxys** [comment]
Maybe my hardcoded wheel id list idea is not so crazy after all  
Could be worth a shot, especially if it's only executed when an untampered wheel list is used
