### ISSUE TITLE
custom key for manual respawn

### ISSUE THREAD

**Issue by super-lurker** [MAFINS/MenyooSP#448]
would love to be able to set the respawn key. thanks

**Comment by itsjustcurtis** [comment]
Are you referring to the toggle under misc options? I think adding a hotkey for that would set a precedent for creating a hotkey for other options, which can get really complex given how many options there are. I can't personally see a purpose for having this hotkeyed over just setting the option in menyoo when it is required.

**Comment by super-lurker** [comment]
I am talking about the revive key it ask you to press to respawn, im a controller user so I'd love to change it over the default RSTICK BUTTON.

**Comment by itsjustcurtis** [comment]
ahh yes. At the moment it is hard-coded, but I may be able to get that functioning. It won't be editable in-game, but I can make it to be modified in the .ini

**Comment by super-lurker** [comment]
ini is fine, looking forward to it.

**Comment by super-lurker** [comment]
just one more tiny request, option to disable the button prompt at the death screen.

**Comment by MAFINS** [comment]
> just one more tiny request, option to disable the button prompt at the death screen.

This won't be pursued. Seems it is a very specific use case.
