### ISSUE TITLE
a better blackout function

### ISSUE THREAD

**Issue by super-lurker** [MAFINS/MenyooSP#454]
using the blackout feature in menyoo disables every light in the game including cars, which doesn't make sense. 
this mods does not have this issue, might worth a look.

https://www.gta5-mods.com/scripts/simple-blackout#description_tab

**Comment by itsjustcurtis** [comment]
I believe this is intended behaviour. Blackout is, as the name implies, a complete blackout of all light sources. Menyoo cannot be expected to over-complicate itself with the functionality of every other mod out there. _If_ this were to be added then I would anticipate needing to add a toggle/selection that allowed users different levels of blackout.

**Comment by MAFINS** [comment]
It can definitely be done with a slider for 2 different modes. 
But I'm not sure how to keep the lights on.
It may be as simple as keeping the lights variables on in the CVehicle struct or calling the native to keep the lights on in a loop,
or it may be more complicated and require tinkering elsehere, or even creating fake lights. It's probably not worth doing the latter, especially if it will require updating for each patch.

**Comment by super-lurker** [comment]
both valid points, I'll leave to you guys then.

**Comment by DaRealVerify** [comment]
> It can definitely be done with a slider for 2 different modes. But I'm not sure how to keep the lights on. It may be as simple as keeping the lights variables on in the CVehicle struct or calling the native to keep the lights on in a loop, or it may be more complicated and require tinkering elsehere, or even creating fake lights. It's probably not worth doing the latter, especially if it will require updating for each patch.

Enhanced Native Trainer has achieved this. Might be worth giving them a call, as I'm sure they'll be happy to point you in the right direction!
