### ISSUE TITLE
I can't spawn peds, and I don't know why. 

### ISSUE THREAD

**Issue by SomeCallMeCringe** [MAFINS/MenyooSP#456]
https://user-images.githubusercontent.com/121494763/209664262-cd746159-4211-4e42-89e9-0dbbe6d81960.mp4

**Comment by MAFINS** [comment]
Make sure all the required files (including PedList.xml) are present in {GTA V directory}/menyooStuff/ 
And that the menyooStuff folder and its contents are not set to read-only.

**Comment by SomeCallMeCringe** [comment]
> Make sure all the required files (including PedList.xml) are present in {GTA V directory}/menyooStuff/ And that the menyooStuff folder and its contents are not set to read-only.

The files are all in there, how do you tell if its set to "Read only?"
![Screenshot (59)](https://user-images.githubusercontent.com/121494763/209671984-37ce6de5-fd5c-433b-940c-a44895951c9e.png)

**Comment by MAFINS** [comment]
@SomeCallMeCringe  The menyooStuff folder should be in the GTA V directory, not the 'mods' directory.

And again, just change the directory's permissions so they are not read-only.

https://cdn.appuals.com/wp-content/uploads/2018/12/Folder-reverts-to-read-only-windows-10.png.webp
