### ISSUE TITLE
How to use Menyoo without bypass

### ISSUE THREAD

**Issue by sPaZMike** [MAFINS/MenyooSP#457]
When i use the mod with Rockstar launcher, it doesnt loads up my vehicles or any other changes. I’ve a “Mod” folder. But, when I used NoGTAVLauncher (a bypass), it used to work. But the launcher doesn’t works with current GTA 5 updates. 

Can someone tell me how do I solve this problem? Because I waited for a whole year for menyoo to come back into development, and now when it did my cars dont load up. Thank you <3

**Comment by MAFINS** [comment]
Your menyooStuff folder should be placed wherever the running executable ends up being in your setup.

**Comment by sPaZMike** [comment]
Any cars are not showing up in the mod. And gameconfig except the Backup isn’t working. Any help? I installed heap, pack limiter, scripthookvdotnet and scripthook. I’ve been trying for so long and searching but nothing is working…..

**Comment by sPaZMike** [comment]
![Uploading B2A7092C-7376-461E-8416-FB428214816A.jpeg…]()

**Comment by sPaZMike** [comment]
![A3359F41-7E2A-4E6F-9B21-BADA084FBCE1](https://user-images.githubusercontent.com/121498500/209698946-65842b0f-318c-45dd-9fbc-d406dc3efb92.jpeg)

**Comment by itsjustcurtis** [comment]
This sounds like a problem with your mod build, rather than Menyoo.

**Comment by sPaZMike** [comment]
I tried changing my dlcpack, reinstalling, editing dlclist.xml (replacing \ -> / and vise versa) but still has the same issue. I don’t want to delete the whole game and do everything bits by bits since there are lots more addons and some nice ones, around 20 gb.

> This sounds like a problem with your mod build, rather than Menyoo.

**Comment by itsjustcurtis** [comment]
Again, this is an issue with your personal build. Not this mod. You need to take the issue to one of the many forums or discord servers for help. 

@MAFINS  you wanna close this issue?

**Comment by sPaZMike** [comment]
> Again, this is an issue with your personal build. Not this mod. You need to take the issue to one of the many forums or discord servers for help.
> 
> @MAFINS you wanna close this issue?

Ok but I didn’t say that the mod is corrupted. I’m just asking for help from the fellow community. That’s all. If I don’t get a solution I’ll go to other forums or discord. Anyways, thanks for suggesting to close this issue. Lolz
