### ISSUE TITLE
Can´t start it

### ISSUE THREAD

**Issue by jafuente** [MAFINS/MenyooSP#46]
Hi from spain:

I am trying to install menyoo to start in the world of mapping for gtaV, but after following the installation instructions, MENYOO does not open in GTAV Single player. Should I consider something else?
I have put ScriptHook and ScripHookDoNet in its latest version but I can't start MENYOO.
Can someone help me please? I dedicate myself professionally to 3D modeling and I would like to investigate the mapping in gta. Thank you.
![image](https://user-images.githubusercontent.com/19649043/63648383-57169980-c72f-11e9-9436-b5b332403dda.png)

**Comment by american9ization** [comment]
I'm also having this same issue, and I know it's Menyoo because the game works fine when I remove the file.

**Comment by MAFINS** [comment]
Are you running the latest update of the game?

**Comment by jafuente** [comment]
Yes...

**Comment by jafuente** [comment]
Some answer?

**Comment by ShawnPR1** [comment]
@jafuente does your game even start at all btw?
I assume it does, but pressing F8 on your keyboard does nothing?

Just to be safe, remove ScriptHookVDotNet entirely seeing as it's not needed for Menyoo to work at all. Maybe even remove NativeTrainer as well and try to run the game with only Menyoo and ScriptHookV.

So the files you'll be left with:
- dinput8.dll
- Menyoo.asi (and the menyooStuff folder)
- ScriptHookV.dll (you can keep the log file for this if you want to)

So in the screenshot you took above, only keep the above files out of the files that are selected.

Hope this helps

**Comment by jafuente** [comment]
Nothing. The same. Menyoo does not open. I don't know what I can do now, the gta is newly installed, I have created a copy of GTA V in another folder so as not to interfere with Roleplay or online mode.
But I don't know what I can do now.

Is it safe that Menyoo works with the latest GTA update?

**Comment by ShawnPR1** [comment]
Menyoo does work in the latest update, yes. I have no issues.

Remove the files I mentioned above and try again. It should work.

**Comment by jafuente** [comment]
Where is the asiloader ? i don´t know if i have install it

**Comment by ShawnPR1** [comment]
ScriptHookV and dinput8.dll handle loading the asi file, don't worry about that.

Yet again: Only use these files: dinput8.dll, ScriptHookV.dll, Menyoostuff folder and Menyoo.asi (for the selected items in your screenshot)
