### ISSUE TITLE
[Suggestion] Utilise RTHE code to add 0x4000000 and 0x8000 to strAdvancedHandlingFlags dynamically

### ISSUE THREAD

**Issue by itsjustcurtis** [MAFINS/MenyooSP#462]
In-game testing has proven that almost all vehicles can have the above flags applied, allowing the Lower Suspension option to work on vehicles that were never intended to have the feature.

IKTs [Real Time Handling Editor](https://github.com/E66666666/GTAVHandlingEditor) has the ability to toggle these flags as requested in game. I theoretically have code that will take a hex input, then add and remove the above if they were not present.

Missing piece at this point is being able to directly manipulate these flags in memory, which I believe can be solved by interrogating the code written by IKT, or with direct assistance.

**Comment by MAFINS** [comment]
I removed most direct memory address fiddling a long time ago to minimise things to update. Even now, things in GTAmemory.cpp haven't been updated in a long time leaving certain things broken. I removed all sorts of structs that the game uses and switched to using native functions as alternatives where possible.

I personally think this will not be manageable in Menyoo.
