### ISSUE TITLE
Menyoo Customs: Pearlescent color selection doesn't have a Paint Index option

### ISSUE THREAD

**Issue by metoxys** [MAFINS/MenyooSP#464]
![image](https://user-images.githubusercontent.com/6764458/209840113-7141e022-c36e-4de7-9ccf-59b87596dde5.png)
This is not the case for the other paint categories

**Comment by metoxys** [comment]
![image](https://user-images.githubusercontent.com/6764458/209840113-7141e022-c36e-4de7-9ccf-59b87596dde5.png)
This is not the case for the other paint categories

**Comment by itsjustcurtis** [comment]
Ahh of course, I think I know why this is. #466 I think is a related issue.
