### ISSUE TITLE
Crashes when applying outfit to MP M/F model

### ISSUE THREAD

**Issue by Trs5405** [MAFINS/MenyooSP#467]
game crashes when applying an outfit to mp m/f model. Error pops on screeen stating error executing menyoo asi.

**Comment by mistahwolf** [comment]
@Trs5405 This is a regular thing if you're using the MPClothes Mod. The workaround is after you spawn in as one of the main 3 characters, open Spooner and spawn in an MP/M/F/freemode ped. Dress them the way you want and then 'Soul Steal' (swap) and become that character. You do this by going into the 'Ped Options Menu' and it's at the bottom of the list. Once you swap, get rid of the F/M/T ped you started out with or they'll hang around the whole time you play. Now you can change outfits 5x (maybe more) before that crashes the game. Not sure why you're crashing if not using MPC, but try this method in the meantime....

**Comment by Trs5405** [comment]
@mistahwolf Thats what ive been doing, but wasnt sure if there was a further work around. Guess ill be removing MPClothes lol
