### ISSUE TITLE
Crashes on OpenVhook

### ISSUE THREAD

**Issue by captian7** [MAFINS/MenyooSP#47]
I updated openvhook to the latest update and it loads nativetrainer just fine but with this it crashes. wasnt sure if i was missing something or what

**Comment by MAFINS** [comment]
OpenVhook is missing a lot of things as far as I am aware

**Comment by MAFINS** [comment]
The sole crashing may be because of the missing exports, however.

**Comment by captian7** [comment]
Oh alright, is there a simple way to fix it or should i just go back to shv? i just liked the way openvhook did things
