### ISSUE TITLE
The weapons list hasn't been updated in a long time

### ISSUE THREAD

**Issue by GalenYang** [MAFINS/MenyooSP#470]
**The Contract (mpsecurity) - 2545**
WEAPON_HEAVYRIFLE
WEAPON_FERTILIZERCAN
WEAPON_EMPLAUNCHER
WEAPON_STUNGUN_MP

**The Criminal Enterprises Update (mpsum2) - 2699**
WEAPON_METALDETECTOR
WEAPON_TACTICALRIFLE
WEAPON_PRECISIONRIFLE

**Drug Wars (mpchristmas3) - 2802**
WEAPON_CANDYCANE
WEAPON_ACIDPACKAGE
WEAPON_PISTOLXM3
WEAPON_RAILGUNXM3

**Comment by MAFINS** [comment]
Do these weapons also have components?

**Comment by GalenYang** [comment]
https://forge.plebmasters.de/weapons

I found it on this website and can view each weapon and their components by DLC category

**WEAPON_HEAVYRIFLE**
COMPONENT_HEAVYRIFLE_CLIP_01
COMPONENT_HEAVYRIFLE_CLIP_02

**WEAPON_EMPLAUNCHER**
COMPONENT_EMPLAUNCHER_CLIP_01

**WEAPON_TACTICALRIFLE**
COMPONENT_TACTICALRIFLE_CLIP_01
COMPONENT_TACTICALRIFLE_CLIP_02
COMPONENT_AT_AR_FLSH_REH

**WEAPON_PRECISIONRIFLE**
COMPONENT_PRECISIONRIFLE_CLIP_01

**WEAPON_PISTOLXM3**
COMPONENT_PISTOLXM3_CLIP_01
COMPONENT_PISTOLXM3_SUPP

**WEAPON_RAILGUNXM3**
COMPONENT_RAILGUNXM3_CLIP_01
