### ISSUE TITLE
Update 1.7.6 broke the customization of some vehicles!

### ISSUE THREAD

**Issue by Pehotinec78** [MAFINS/MenyooSP#474]
The armored personnel carrier does not change coloring. When replacing a gun with a missile system, there will be an empty space on the roof of the armored personnel carrier. The same goes for Half-track. The rest did not check. Installed version 1.7.5 back, everything is fine there.

**Comment by metoxys** [comment]
![image](https://user-images.githubusercontent.com/6764458/210152787-89c41f73-f923-4aeb-b3b4-71d7e78cc7f0.png)
Tested using the latest version  
I can't replicate your problem

**Comment by Pehotinec78** [comment]
> ![image](https://user-images.githubusercontent.com/6764458/210152787-89c41f73-f923-4aeb-b3b4-71d7e78cc7f0.png) Tested using the latest version I can't replicate your problem

Ok, I'll try to install and test again.

**Comment by Pehotinec78** [comment]
> ![image](https://user-images.githubusercontent.com/6764458/210152787-89c41f73-f923-4aeb-b3b4-71d7e78cc7f0.png) Tested using the latest version I can't replicate your problem

I'm sorry, it's my fault. It's just that the custom did not load, it was necessary to wait a bit. I close the topic.
