### ISSUE TITLE
Menyoo crashing when applying female model: an exception occurred executing native 0xc8a9481a01e63c28 in a ViSH plugin (0x7ffe3fb901ee - adhesive.dll+34E01EE)

### ISSUE THREAD

**Issue by Dragon10933** [MAFINS/MenyooSP#476]
I was playing on my fivem server and trying to apply a female model, then suddenly the client crashed on me. I keep getting this error "an exception occurred executing native 0xc8a9481a01e63c28 in a ViSH plugin (0x7ffe3fb901ee - adhesive.dll+34E01EE)." I've been stuck on this issue for a very long time and i think this is due to the fact i have too many clothing mods installed for the client. Please any help would be appreciated.

**Comment by MAFINS** [comment]
I think someone mentioned at some point that there was some issue with SET_PED_RANDOM_COMPONENT_VARIATION with a fix for it. Hopefully they can provide some incite if they see this.

**Comment by Dragon10933** [comment]
@itsjustcurtis Yes and I'm still having the same issue. I've got v1.7.6

**Comment by SpoonNamedJamie** [comment]
I've got the same issue with vehicles

**Comment by Dragon10933** [comment]
It's happening when i add new clothing mods to the fivem server and it crashes menyoo

**Comment by MixJesteR** [comment]
Any fixes?
