### ISSUE TITLE
Character leaving MP vehicles after entering them

### ISSUE THREAD

**Issue by SenShiza** [MAFINS/MenyooSP#483]
Everytime I try to use an MP vehicle spawned with menyoo the character always leaves the vehicle randomly after entering it. It does not happen with normal story mode vehicles. Anyone have the same problem?

**Comment by mistahwolf** [comment]
@SenShiza, Peds spawned in Spooner and given 'task' to follow will get into a vehicle, but will get out the moment you stop even if it's just at a light. Haven't heard of a player controlled ped doing that.

**Comment by SenShiza** [comment]
@mistahwolf Here is a video about how this issue occurs, it never happened before and I don't have any other mod installed apart from a ymap, fuel script mod and a vehicle control mod:
[https://vimeo.com/789119797](url)

**Comment by itsjustcurtis** [comment]
Before we can investigate, we'd need you to confirm that menyoo is definitely the cause. Remove both your script mods and try again. If the issue persists, please send another video with a few different vehicles so I can try to replicate

**Comment by SenShiza** [comment]
So after removing Menyoo, then using Trainer V for spawning the MP cars and not having the bug again, reinstalling Menyoo again suddenly the bug is gone. I don't know what was the cause but we can figure out it wasn't menyoo it was just a weird bug
