### ISSUE TITLE
[Bug] HasSiren detection detects Mule has a siren

### ISSUE THREAD

**Issue by WithLithum** [MAFINS/MenyooSP#486]
![Screenshot](https://user-images.githubusercontent.com/37800788/213392904-9fbda70e-5d13-4e5d-9120-27caf74b11e2.png)

### Description
`HasSiren` method that was used to resolve the issue #436 works incorrectly and presumably detected an incorrect bone which caused most vehicles do not have Siren features even if they were supported before the commit dfdf278e.

### Excepted behaviour

Only vehicles that has `siren1` will have Siren options support.

### Actual behaviour

A weird set vehicles (some do have siren, some do not) have siren options support regardless of whether or not they actually have siren.

### Workarounds

- Enable siren manually by getting into the vehicle, then press Horn (default `E`) to enable/disable siren, before putting any peds into it.
- Soul-steal the driver (the driver has to be in the Object Spooner Database) and manually enable/disable siren before soul-stealing back to the player.

### Notes

- It is possible that something is wrong with `VBone::siren1` (for example, pointing to a completely different bone) that caused the detection to go wrong.
- `siren1` _do_ show up in the bone list of the attachment menu (of vehicles that do have such bone).

**Comment by metoxys** [comment]
It also detects the BR8 has a siren (maybe other open wheelers as well)

**Comment by itsjustcurtis** [comment]
Looking into this, it looks like the vehicle bone list is out-dated. That said, using the latest bone list appears to remove the option for _all_ vehicles. Going to investigate dynamic bone indexes to let the game tell menyoo what indexes it should be looking for.

**Comment by MAFINS** [comment]
Well for some reason the enum VBone::VBone and the string array VBone::vNames are completely different in order. One or the other needs re-ordering.

**Comment by itsjustcurtis** [comment]
I'm doing some unrelated changes at the moment, can easily do that while
I'm in here and test
