### ISSUE TITLE
Menyoo can't save map, create files or directory

### ISSUE THREAD

**Issue by Culvanen** [MAFINS/MenyooSP#50]
Hi, when i try to save my map menyoo return a error message: unable to save file.
same for directory create.

Thanks

**Comment by MAFINS** [comment]
Make sure that the menyooStuff folder is not set to read-only.

**Comment by RedRiot100** [comment]
Hello, I have the same problem on my Gta V so I followed your conversation and I tried to deactivate "Read only" except that it gives me an error message (you must have the rights to administrator to modify these attributes.)
Now when I reopen the file, I see it in "Read only"

**Comment by TheyRuslan** [comment]
> Hi, when i try to save my map menyoo return a error message: unable to save file. same for directory create.
> 
> Thanks

you know how fix it?
