### ISSUE TITLE
Eye makeup is not the same when loading a xml female ped

### ISSUE THREAD

**Issue by Dragon10933** [MAFINS/MenyooSP#504]
I noticed that whenever I loaded a friend's character, some of eye makeups are totally different to what is shown to me via their screenschot. For example, if you apply the "vamp" makeup on the character it has the distinctive of the white and black around the eyes and when i load the file on menyoo and it changes. The makeup colour is more darker than the original. How do you fix this? Any help with be appreciated.

**Comment by MAFINS** [comment]
Could have something to do with 14fbe6a [Add makeup color modifier](https://github.com/MAFINS/MenyooSP/pull/465).
If  someone could shed some light, it would be appreciated.

**Comment by GalenYang** [comment]
Did your friend send you a character that was only generated and modified by menyoo? No other trainers were used in the process?

**Comment by GalenYang** [comment]
I also use FiveM, but my save works fine. You can try these files of mine.

![F_Black](https://user-images.githubusercontent.com/19515739/216362716-76690242-1dff-4b07-a6a5-dbcfb0c1c3b0.png)

![M_Shirt](https://user-images.githubusercontent.com/19515739/216362792-57f99c29-74fa-4052-a590-c1a2436e677d.png)

[https://letsupload.cc/T2c183Vcye/Outfit_zip](url)

**Comment by Dragon10933** [comment]
@GalenYang what version are you using, I may ask?

**Comment by Dragon10933** [comment]
And I just saw my friend load in their character in my server. It's working for them, but still not working for me...

**Comment by GalenYang** [comment]
GTA V build 2802 / Online 1.64
FiveM Ver.6209 / server 5848

It looks like your game or setup is faulty, not menyoo

**Comment by Dragon10933** [comment]
How do i fix it for fivem?

**Comment by GalenYang** [comment]
I can't figure out exactly what went wrong, but try to reinstall the FiveM client and rebuild your server. Good luck.

https://docs.fivem.net/docs/client-manual/installing-fivem/
https://docs.fivem.net/docs/server-manual/setting-up-a-server-vanilla/

**Comment by Dragon10933** [comment]
Hmm, i tried reinstalling and rebuilding my server. still shows the same results

**Comment by GalenYang** [comment]
I may have found the problem, the version of the game in FiveM.
Look for the watermark in the upper right corner
Mine is b2699 and yours is b1604

![2023-02-03 (9)](https://user-images.githubusercontent.com/19515739/216573494-2e08ff71-dd1a-4c98-9027-3cc32dd9a9d8.png)


I think your friend is using another mod or photo filter. If you load the same outfit as the one I sent you, your game is fine.

If you want to update to version b2699, add this line  "+set sv_enforceGameBuild 2699" to server.cfg or FiveM.cmd
![2023-02-03 (10)](https://user-images.githubusercontent.com/19515739/216574976-77cf694c-264c-4ed9-afa2-10e47b1b549e.png)

**Comment by Dragon10933** [comment]
I changed back the game build, but i'm still facing the same issue. And my friends are not using any mods or photo filters. I am using a mod that enhances player's faces to show less wrinkles, but I've always had this issue before i installed this mod. This was taken yesterday:
![image](https://user-images.githubusercontent.com/121786063/216579611-a9405309-cd9a-4ab2-acc6-75c8a72fb895.png)

And this is now with your character @GalenYang:
![image](https://user-images.githubusercontent.com/121786063/216579819-9f9e4ab2-0d1c-4c17-b1a3-88aaffcf3824.png)

**Comment by Dragon10933** [comment]
Nevermind, i resolved it lol. i just need to recreate them. the make up works now xD. I appreciate your support @GalenYang
