### ISSUE TITLE
Eye makeup changes when you load a save file

### ISSUE THREAD

**Issue by Dragon10933** [MAFINS/MenyooSP#508]
Back to my old issue #504, i doing some experimentation on the makeup and face paint and noticed that when you apply the make up first time, it looks as it is. However, when I alter the primary colour at least once and revert back to normal it still stays as black. Same goes for loading an outfit. The eye makeup default colour is black for some reason. I noticed none of my friends has this issue, just me. How do i fix this?
Before:
![image](https://user-images.githubusercontent.com/121786063/216591972-6504dd7d-ef6a-42e2-b58e-97e1cb345def.png)

After: 
![image](https://user-images.githubusercontent.com/121786063/216592542-ac22d589-6e4f-4f85-8f08-63bc2bb095d4.png)

**Comment by CharlieGib** [comment]
I'm having this issue as well. Loading xmls have this makeup bug, but when I spawn a freemode female npc, the make up looks normal. Even when I don't use menyoo and use my online character in director mode, she will have this bug.

**Comment by Dragon10933** [comment]
I downgraded my menyoo version back to 1.7.5 before https://github.com/MAFINS/MenyooSP/commit/14fbe6af113f50a752821297b2b86239e3914746 https://github.com/MAFINS/MenyooSP/pull/465. And anything above version 1.7.5 has the bug. Can someone look into this and fix this please?

**Comment by CharlieGib** [comment]
By the way @Dragon10933 I would like to thank you, this issue has been bugging me for 2 days. Your method fixed it for me :)

**Comment by MAFINS** [comment]
See 0b72c64d8af401ba72365d9759bbc3f86f110392
and f4ea134a5c4a99c3c3d511822d609c1a46cd9bcc

This may resolve the issue but I'm not sure

**Comment by GennosukeDono** [comment]
Good day. I have this bug too if I use the latest (1.8.1) version of Menyoo: loading a MP xml outfit makes it impossible to have a neutral color makeup, even if the selected color is 0.

Reverting to version 1.7.5 fixes the issue since it doesn't have the option to chang the color of the makeup. 

A fix would be neat.
