### ISSUE TITLE
Some vehicles crash the game when spawning!

### ISSUE THREAD

**Issue by Pehotinec78** [MAFINS/MenyooSP#526]

**Comment by metoxys** [comment]
Maybe you are trying to spawn E&E vehicles like the Cyclone II or Weaponized Ignus  
since they're not properly included in the game files, they will crash the game regardless of what spawns them  
not a Menyoo-specific issue

**Comment by Pehotinec78** [comment]
> Maybe you are trying to spawn E&E vehicles like the Cyclone II or Weaponized Ignus since they're not properly included in the game files, they will crash the game regardless of what spawns them not a Menyoo-specific issue

Is it possible to at least remove them from the vehicle spawn list ? Since in the "object spooner" mode, one has only to go to the section with a faulty vehicle, it immediately crashes. Very tired of restarting the game a hundred times.

**Comment by nomakewan** [comment]
I just tested spawning the stub vehicles with the latest build of Menyoo and GTAV 2845. The vehicle spawner will not allow you to spawn those vehicles; nothing happens if you try, even though they appear in the list. The vehicle spawner will also not allow you to spawn the vehicles if you manually input the model. The object spooner will not allow you to spawn these vehicles if you try to spawn them as a vehicle, either, nor will the vehicle section allow you to manually input the name to spawn them. If you instead spawn the model as an object using the manual name input, it will attempt to spawn the object, but it'll just be an invisible entity.

No crashes at all whether spawning normally or using Spooner Mode.

**Comment by Pehotinec78** [comment]
> I just tested spawning the stub vehicles with the latest build of Menyoo and GTAV 2845. The vehicle spawner will not allow you to spawn those vehicles; nothing happens if you try, even though they appear in the list. The vehicle spawner will also not allow you to spawn the vehicles if you manually input the model. The object spooner will not allow you to spawn these vehicles if you try to spawn them as a vehicle, either, nor will the vehicle section allow you to manually input the name to spawn them. If you instead spawn the model as an object using the manual name input, it will attempt to spawn the object, but it'll just be an invisible entity.
> 
> No crashes at all whether spawning normally or using Spooner Mode.

Well, I now went into the game to test. In the "object spooner" mode, I entered the list of vehicles in the "SUVs" section and I crashed because of a car called "ASTRON2".

**Comment by Pehotinec78** [comment]
The same thing happens in the "Muscle" section. The very first car in this section crashes me.

**Comment by nomakewan** [comment]
I am not able to replicate your experience. Here is a video of me attempting exactly what you described: https://www.youtube.com/watch?v=tvATatckluw

**Comment by Pehotinec78** [comment]
> I am not able to replicate your experience. Here is a video of me attempting exactly what you described: https://www.youtube.com/watch?v=tvATatckluw
Strange. I don't really understand what's going on.

**Comment by nomakewan** [comment]
What version of GTAV are you on? Are you using vanilla, or are you using Rage Plugin Hook (LSPDFR, etc)? Do you have any other mods installed which might be modifying the stub models?

I'm on 2845, vanilla, and no mods that would mess with the stub vehicles. Curious what your install is like.

**Comment by Pehotinec78** [comment]
> What version of GTAV are you on? Are you using vanilla, or are you using Rage Plugin Hook (LSPDFR, etc)? Do you have any other mods installed which might be modifying the stub models?
> 
> I'm on 2845, vanilla, and no mods that would mess with the stub vehicles. Curious what your install is like.

I use version 2845. Vanilla. Menyoo Version 1.8.1. Also, I have a second trainer "Rampage". I have quite a few military vehicle mods from "SkylineGTRFreak". But I don't have dlc mods called "ASTRON2". By the way, after watching your video above, I noticed that you do not have it in the list of the "SUVs" section. After "Astron" you have "Astron custom". I do not have "Astron custom", but there is an incomprehensible "ASTRON2". It's strange like that.

**Comment by nomakewan** [comment]
Now we're onto something! Yet again it appears this is not Menyoo's fault.

Menyoo populates the list of vehicles by calling `GTAmemory::GenerateVehicleModelList()` which is in GTAmemory.cpp, line 836. It's doing an actual memory analysis of your current GTAV install as-is. So indeed, one of your mods, or Rampage trainer, is modifying the game in a way Menyoo does not expect.

First, test removing Rampage temporarily and see if that makes your menu look like mine. If that does not resolve the issue, and you have the space, try installing a second copy of GTAV without those military vehicle mods and see if that resolves it.

I've tested on both Menyoo 1.8.1 and the latest source build, and in both cases there is no crash. This must be something in your install. If we can figure out what, there might be a way to figure out a workaround. Thank you for any assistance you can provide!

**Comment by Pehotinec78** [comment]
> 

Okay, I'll try to test your advice step by step. As for the language, the Menyoo are mostly in English, with only a few passages translated into Russian.

**Comment by nomakewan** [comment]
Ah, okay, so your GTAV is set to Russian? So it's using another language. That's good to know.

Thank you again for testing! Hopefully we can get to the bottom of this.

**Comment by Pehotinec78** [comment]
> Now we're onto something! Yet again it appears this is not Menyoo's fault.
> 
> Menyoo populates the list of vehicles by calling `GTAmemory::GenerateVehicleModelList()` which is in GTAmemory.cpp, line 836. It's doing an actual memory analysis of your current GTAV install as-is. So indeed, one of your mods, or Rampage trainer, is modifying the game in a way Menyoo does not expect.
> 
> First, test removing Rampage temporarily and see if that makes your menu look like mine. If that does not resolve the issue, try temporarily moving the mods and scripts folders out of the GTAV folder. Put them somewhere else safe. Then try again; this should mean you'll be on a completely vanilla GTAV, but with Menyoo available.
> 
> I've tested on both Menyoo 1.8.1 and the latest source build, and in both cases there is no crash. This must be something in your install. If we can figure out what, there might be a way to figure out a workaround. Thank you for any assistance you can provide!
> 
> EDIT: Also, what language is GTAV using? Is it English? I see someone using Simplified Chinese just opened an issue claiming the trainer crashes when that language is used. Since the process to populate the vehicle list does use the native to request the localized name of the vehicle, it makes me wonder if that could also be a factor.

Yes, you are right, the problem is not in the menu, but in my mods. By removing the "mods" folder, I stopped crashing because of these vehicles. I don’t even know what mods can conflict with these cars. I have military equipment in the form of DLS mods, sounds for weapons, police sirens. I also have the heavy mod "Vanilla Expanded: Dispatch, Gang and Action" by "x3mgamer" installed. Hard to say. Now I will not delve into the mod, there is no desire. Thanks for helping me. Glad the menu isn't to blame.

**Comment by nomakewan** [comment]
Glad I could help! I have a feeling it's that "Vanilla Expanded" that's messing around with stuff in a way Menyoo doesn't like. I'll investigate those mods and see if there's something that jumps out at me about them. Thank you again for helping test! For now, it would be good to close this issue as it is not necessarily a Menyoo problem. Still, I will do some digging and see if this issue really is a one-off or if there is a robust workaround that can be implemented to make Menyoo handle these situations better.

Peace!

**Comment by Pehotinec78** [comment]
> Glad I could help! I have a feeling it's that "Vanilla Expanded" that's messing around with stuff in a way Menyoo doesn't like. I'll investigate those mods and see if there's something that jumps out at me about them. Thank you again for helping test! For now, it would be good to close this issue as it is not necessarily a Menyoo problem. Still, I will do some digging and see if this issue really is a one-off or if there is a robust workaround that can be implemented to make Menyoo handle these situations better.
> 
> Peace!

Thanks!
