### ISSUE TITLE
Infinite Native Boost not working

### ISSUE THREAD

**Issue by jpmend** [MAFINS/MenyooSP#53]
When I activate the Infinite Native Boost option, nothing changes. It used to work on v1.0.1.
 Please help me...

**Comment by MAFINS** [comment]
It's because there was a gta v patch update (something I only just found out about).
If someone could update all these addresses, that'd be great. In fact, you'd just need to add the new version number as a switch case for these since, I think.

**Comment by jpmend** [comment]
Thx! Do I need to downgrade the version?

Em dom, 29 de set de 2019 11:36, MAFINS <notifications@github.com> escreveu:

**Comment by Leve1** [comment]
just created pull request with fix

**Comment by jpmend** [comment]
Thank you

Em ter, 1 de out de 2019 22:11, Leve <notifications@github.com> escreveu:

**Comment by MAFINS** [comment]
You'll be able to download that version from the appveyor build once I approve it (I requested some changes atm)
