### ISSUE TITLE
Trouble with finding the key-binds (integer values) correlating to controller inputs for the 'config.ini' file.

### ISSUE THREAD

**Issue by JasonSmiggy18** [MAFINS/MenyooSP#531]
Hello there, quick question if you could respond to this thread.

I understand that you conveniently left a link for user access of key-binds to use for keyboard and controller setups. However, the frustrating thing at the moment is that the link has not been accessible, and I am unable to find the key-bindings anywhere for the 'config.ini' file. 

Essentially, I am trying to change the buttons for opening and closing the menu from the default keys to new ones, and thus I would need to know the integer values for the controller buttons.

Please get back to me with some help, if you can. It would be helpful to understand how these integer values are to be found in the future, or how they are determined. ScriptHookVDotNet has very similar numbers, but they do not seem to be the same. 

P.S. I am not really a developer by any means, but I have taken a few classes on computer science for basic principles; mostly Python and just a little bit of Java or C++ based languages. So I don't understand a whole lot of everything, especially more specific stuff like this particular case-issue.

Thanks.

**Comment by nomakewan** [comment]
http://www.foreui.com/articles/Key_Code_Table.htm

**Comment by JasonSmiggy18** [comment]
This is pretty helpful, thank you.

I wasn't expecting there to be a number for each application or use in-game of a key bind, rather just the number for the button being pressed.
I suppose I will have to sort out which of the particular decimal number to use for the same controller key, as it is owned by multiple actions.

Anyways, its reasonable. 
Thank you.
