### ISSUE TITLE
Menyoo breaks the game after first opening the menu

### ISSUE THREAD

**Issue by dev-kamran2001** [MAFINS/MenyooSP#546]
Last time I played GTA 5 was about 9 months ago, I did not have issues with menyoo at that time but now when I open the menu the game breaks and crash after a minute or two.

First after opening the menu nothing suspicious happens but as soon as I walk around or drive with a car I start to see some weird glitches like distant lights (not cars light) flickering, a minute or two later the game screen freezes and I just able to hear sounds like my car driving but not crashing into another car or a wall.

I'm using the latest steam version of the game at this time, installed mods are only HeapAdjuster and ScriptHookV plus the Dotnet version after uninstalling many to find which one causing the issue.

[menyooLog.txt](https://github.com/MAFINS/MenyooSP/files/11203114/menyooLog.txt)
Also I'm running the game with DirectX 10.

**Comment by metoxys** [comment]
asiloader and scripthook logs are probably much more meaningful in this situation

**Comment by dev-kamran2001** [comment]
Well, after another one hour of tests and gameplay since opening this issue here I'm now pretty sure the asiloader itself (no any mods of any kind installed, just the loader) are causing this issue. Menyoo just made it to appear much earlier for some reason.

I know now this is not related to Menyoo anymore, but any suggestions what to do? the problem with the loader itself seems extremely rare since I cant find anything on the internet about it.

**Comment by metoxys** [comment]
Try using the asi loader that comes with ScriptHookV? Never had any issues, and that's what I've been using for years
