### ISSUE TITLE
MSNeons crashes?

### ISSUE THREAD

**Issue by MAFINS** [MAFINS/MenyooSP#55]
"So basically when you go on menyoo then vehicles then menyoo customs and finally neon lights and try to open the submenu it crashes ur gta." -user

https://github.com/MAFINS/MenyooSP/blob/e2fd2ac298c124688ab3e8049567e9ff0afae85b/Solution/source/Submenus/VehicleModShop.cpp#L2884-L2920

**Comment by SaggyBlackSack** [comment]
It doesn't crash my game, I am running on the Feb 27 2019 version. I don't get why you people even update your scripts / game once it's all stable. Though unfortunately I deleted my old Menyoo.asi. Any chance you can give me what ever version was up in around July/August pleasee>!!??!!?>!?

**Comment by MAFINS** [comment]
> It doesn't crash my game, I am running on the Feb 27 2019 version. I don't get why you people even update your scripts / game once it's all stable. Though unfortunately I deleted my old Menyoo.asi. Any chance you can give me what ever version was up in around July/August pleasee>!!??!!?>!?

Oder versions can be found on the gta5-mods Menyoo page, in the side panel.


I still, however, would like to know if this is crashing on the latest version...

**Comment by SaggyBlackSack** [comment]
Hey thanks for the advise but there isn't enough of a back log of versions on gta5-mods.com for me to get the July version. I'm not sure what one that would of been, it's just the compilied .asi that I would like. It is only a tiny bug that it would fix for me, and that is custom xenon headlights. 

Also, so you're mafins, you run the mod and the pages now, right... but who's the original programmer of this brilliant enabler to create videos and scenes? This is an amazing addition to what all us aspiring game developers can do with R*'s game and their work hours - how it translates into learning for us.

Thanks whoever you are mafins! One love one hustle one puddle of wet

**Comment by MAFINS** [comment]
> Hey thanks for the advise but there isn't enough of a back log of versions on gta5-mods.com for me to get the July version. I'm not sure what one that would of been, it's just the compilied .asi that I would like. It is only a tiny bug that it would fix for me, and that is custom xenon headlights.
> 
> Also, so you're mafins, you run the mod and the pages now, right... but who's the original programmer of this brilliant enabler to create videos and scenes? This is an amazing addition to what all us aspiring game developers can do with R*'s game and their work hours - how it translates into learning for us.
> 
> Thanks whoever you are mafins! One love one hustle one puddle of wet

I wrote the mod but I don't work on it anymore, hence why I made the source public under a gpl.

What is the issue with the xenon lights? The same issue of it being stuck on "Stock"?

**Comment by MAFINS** [comment]
Also, is this really an issue on the latest version (Neons submenu crashing)? I would like to close this issue if it isn't.

**Comment by SaggyBlackSack** [comment]
It 100% is my friend. I don't crash, personally, but it is certainly stuck and broken
