### ISSUE TITLE
How to turn off color preview on cars? [SOLVED]

### ISSUE THREAD

**Issue by Gta5KoRn** [MAFINS/MenyooSP#635]
With new menyoo versions, when i choose a color on a car, it autmatically applies it on it. And after this it has to be confirmed with "enter". How to turn this off, its very annoying. I need to find out color ids while making a mod, especially when i choose pearleascent it applies the color so i cant even check the id... :/

**Comment by metoxys** [comment]
Scroll down in Menyoo Customs and disable LSC style part selection

**Comment by Gta5KoRn** [comment]
> Scroll down in Menyoo Customs and disable LSC style part selection

thats it. Thanks for the reply!

**Comment by metoxys** [comment]
FYI, changing the title of an issue doesn't actually close it  
There should be a `Close issue` button for you somewhere
