### ISSUE TITLE
Cars Despawning instantly

### ISSUE THREAD

**Issue by Renthner** [MAFINS/MenyooSP#643]
Hey there, I just downloaded ScriptHookV and MenyooSP, everything is the newest version existing but when I try to Spawn Vehicles from the Online Mode they just instantly disappear again...

**Comment by The-UnXplained** [comment]
https://github.com/MAFINS/MenyooSP/issues/642

**Comment by Renthner** [comment]
> #642 - fixes this issue.

Thank you very much for your helpful reply. It in fact helped and I can spawn all vehicles now :)

> ahaha real clown) Sad? stop spam your shit miner version

Also thank you very much for your not so helpful and kinda insulting reply. You didn't help me - someone who just asked his first ever question in this case - at all.

Hope you both have a great day 🫶🏼

#closed

**Comment by vbelevcev** [comment]
> > #642 - fixes this issue.
> 
> Thank you very much for your helpful reply. It in fact helped and I can spawn all vehicles now :)
> 
> > ahaha real clown) Sad? stop spam your shit miner version
> 
> Also thank you very much for your not so helpful and kinda insulting reply. You didn't help me - someone who just asked his first ever question in this case - at all.
> 
> Hope you both have a great day 🫶🏼
> 
> #closed
successful cleaning of the computer from the miner and its traces,

**Comment by The-UnXplained** [comment]
@Renthner You're welcome buddy.
