### ISSUE TITLE
new patch apparently

### ISSUE THREAD

**Issue by MAFINS** [MAFINS/MenyooSP#66]
Recording UI: 0x56c3 + 0x82
MP vehicle despawn: 4268190
version number?

**Comment by metoxys** [comment]
FYI, scripthook is updated now

**Comment by metoxys** [comment]
New MP vehicles aren't despawning for me, they seem to work fine

**Comment by labzz** [comment]
My cars from the old update and the new one stopped appearing

**Comment by MAFINS** [comment]
@labzz 
Fix for now: https://ci.appveyor.com/api/buildjobs/o2765t1hf8ge83a2/artifacts/MenyooSP.zip

**Comment by labzz** [comment]
@MAFINS 
yes, everything works, thanks a lot bro
