### ISSUE TITLE
Menyoo Won't Work

### ISSUE THREAD

**Issue by IWantWORKINGMods** [MAFINS/MenyooSP#77]
I have been waiting to use menyoo after a while now and it won't work like at ALL. Everything is installed properly even looked at some YouTube video's and still nothing. Load into game hit the default F8 and..nothing not even a loaded sign. I have disabled anti virus and nothing worked. Anyone got any solutions?

**Comment by MAFINS** [comment]
What do the scripthook logs say?

**Comment by RomchickHHH** [comment]
I have the same problem
