### ISSUE TITLE
Missing vehicle attatchment options.

### ISSUE THREAD

**Issue by ReadyP1ayerTwo** [MAFINS/MenyooSP#86]
My game is up to date on the lastest version of 1.0.1868.0, And menyoo is also up to date at the current version of 1.3.0. Menyoo is the only mod i am using. I Would like to add that i am using Menyoo on FiveM. As far as any logs go, I Can't find them for the asi-five.dll, scripthookv.dll, And the scripthookvdotnet doesn't show up anywhere in my fivem files. FiveM Does not require you to modify the base game files in order to use mods in the FiveM client.

I noticed while trying to attach an object to my vehicles wheels that there were only three options. Bodyshell, Bonnet, And afterburner. Once i select the afterburner option, It gets stuck and i can't select another bone to attach to. I Can detach the object and re-attach it to the vehicle so i can select another bone to attach to, But i am still stuck with those three options, Bodyshell, Bonnet, And afterburner.

**Comment by ReadyP1ayerTwo** [comment]
My bad. I Noticed that you can actually click on the bone attachment and it opens a whole list of other bones to attach to. My whole time using this menu i thought you just couldn't attach to things like the wheels. Hope this helps someone!

**Comment by MAFINS** [comment]
Yeah, sorry about the confusion.
The slider shouldn't be too hard to fix, though, if anyone wanted to.
Or someone can just remove the slider entirely, I guess.

**Comment by ReadyP1ayerTwo** [comment]
Not a problem man. Glad to see menyoo is still around! My all time favorite menu. Super happy i can use it in FiveM too.
