### ISSUE TITLE
Casino Cars despawn 

### ISSUE THREAD

**Issue by mamadrol007** [MAFINS/MenyooSP#90]
If I try to spawn a car from the Casino or Casino Heist DLC it despawns shortly after. I alredy reported this problem in december but my game chrashed and I had to re install the menyoo mod. Last time you gave me a difrent file and it worked can you please send it again ? Thanks

**Comment by MAFINS** [comment]
https://ci.appveyor.com/api/buildjobs/814gfovutj0kax43/artifacts/MenyooSP.zip

**Comment by mamadrol007** [comment]
Sorry @MAFINS but this one has the same problem.
